//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <ctype.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t append_log(char * a1, int32_t a2);
int32_t flush_all_ram_log(void);
int32_t flush_ram_logs(uint32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t freeset(int32_t a1, int32_t * a2, int32_t a3, int32_t a4);
int32_t get_boot_seq(int32_t a1, int32_t a2, int32_t a3);
int32_t get_checksum_constprop_3(int32_t a1, int32_t a2, int32_t a3);
int32_t get_first_ram_log(int32_t a1, int32_t a2, int32_t a3);
int32_t get_log_line_from_buffer(void);
int32_t get_next_ram_log(int32_t a1, int32_t a2);
int32_t md5_init(int32_t * a1, int32_t result, int32_t a3);
char * md5_process(int32_t a1, char * a2);
int32_t p_b_coll_elem(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t p_b_symbol(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t p_count(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t ram_logger_early_init(int32_t a1, int32_t a2, int32_t a3);
int32_t ram_logger_init(int32_t a1, int32_t a2);
int32_t ram_logger_output(char * a1);
int32_t seterr(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);

// --------------------- Global Variables ---------------------

int32_t g20 = 0; // LR
int32_t g21 = 0; // R0
int32_t g22 = 0; // R1
int32_t g23 = 0; // R10
int32_t g24 = 0; // R11
int32_t g25 = 0; // R2
int32_t g26 = 0; // R4
int32_t g27 = 0; // R5
int32_t g28 = 0; // R6
int32_t g29 = 0; // R7
int32_t g30 = 0; // R8
int32_t g31 = 0; // R9
char * g1; // 0x8f6576f8
char * g2; // 0x8f657e58
char * g3 = "\x01"; // 0x8f6a4258
char (*g4)[4] = "SOH"; // 0x8f6a4524
char * g5 = "\x01"; // 0x8f6aff30
char g6 = 0; // 0x8f6aff5c
char * g7 = "\x01"; // 0x8f6aff80
char * g8; // 0x8f6ed810
int32_t g9 = 0; // 0x8f6ed814
int32_t g10 = 0; // 0x8f6ed818
int64_t g11 = 0; // 0x8f6ed820
int32_t g12 = 0; // 0x8f6ed824
int32_t g13 = 0; // 0x8f6ed828
int32_t g14 = 0; // 0x8f6ed82c
int32_t g15 = 0; // 0x8f6ed830
char * g16; // 0x8f6ed834
int32_t g17 = 0; // 0x8f6ed838
int32_t g18 = 0; // 0x8f70da8d
char * g19; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f6578fc - 0x8f657baf
int32_t flush_all_ram_log(void) {
    int32_t v1 = g26; // 0x8f6578fc
    int32_t v2 = g27; // 0x8f6578fc
    int32_t v3 = g28; // 0x8f6578fc
    g24 = (int32_t)&g19;
    char * v4 = g19;
    int32_t v5 = g15;
    g30 = v5;
    char v6 = *(char *)&g7; // 0x8f65791c
    if (v6 != 0) {
        // 0x8f657b78
        if (v4 != g19) {
            // 0x8f657b88
            __stack_chk_fail();
            // branch -> 0x8f657b8c
        }
        // 0x8f657b8c
        g26 = v1;
        g27 = v2;
        g28 = v3;
        return g21;
    }
    int32_t * v7 = (int32_t *)(v5 + 28); // 0x8f657928_0
    uint32_t v8 = *v7; // 0x8f657928
    if (v8 != 0) {
        if (v8 > 0x1ffe00) {
            // 0x8f657940
            *v7 = 0x1ffe00;
            *(int32_t *)(g30 + 32) = 512;
            *(int32_t *)(g30 + 24) = (int32_t)v6;
            *(int32_t *)(g30 + 36) = 0x200000;
            v5 = g30;
            // branch -> 0x8f657958
        }
        int32_t * v9 = (int32_t *)(v5 + 24); // 0x8f657958_0
        uint32_t v10 = *v9; // 0x8f657958
        int32_t v11 = v5; // 0x8f6579b4
        if (v10 % 4 != 0) {
            int32_t v12 = v10 & -4; // 0x8f657964
            *v9 = v12;
            *(int32_t *)(g30 + 32) = *(int32_t *)(v5 + 32) + v12 - v10;
            int32_t * v13 = (int32_t *)(g30 + 28); // 0x8f65797c_0
            *v13 = v10 + *v13 - v12;
            v11 = g30;
            // branch -> 0x8f65798c
        }
        uint32_t v14 = *(int32_t *)(v11 + 28); // 0x8f65798c
        g31 = v14;
        g23 = &g13;
        uint32_t v15 = *(int32_t *)(v11 + 24); // 0x8f65799c
        uint32_t v16 = g13;
        uint32_t v17 = *(int32_t *)(v11 + 20) + v15; // 0x8f6579bc
        int32_t v18 = v17 + v16; // 0x8f6579c8
        g26 = v18;
        int32_t v19 = (int32_t)(v17 < v15) + g14 + (int32_t)(v18 < v17); // 0x8f6579cc
        g27 = v19;
        int64_t v20 = g11;
        int32_t v21 = v20;
        uint32_t v22 = v21 + v16; // 0x8f6579d4
        uint32_t v23 = g12 + g14 + (int32_t)(v22 < v16); // 0x8f6579d8
        bool v24 = false; // 0x8f6579e4
        bool v25 = v19 >= v23; // 0x8f6579e4
        if (v19 == v23) {
            // if_8f6579e0_0_true
            v24 = v18 == v22;
            v25 = v18 >= v22;
            // branch -> after_if_8f6579e0_0
        }
        int32_t v26 = v18; // 0x8f657a888
        if (!v24 && !((v25 ^ true))) {
            // 0x8f6579e8
            __aeabi_uldivmod((int64_t)(v18 - v22), v20);
            uint32_t v27 = v16 + 512; // 0x8f657a00
            int32_t v28 = v21 + v27; // 0x8f657a08
            g26 = v28;
            int32_t v29 = (int32_t)(v16 > 0xfffffdff) + g14 + (int32_t)(v28 < v27) + g12; // 0x8f657a0c
            g27 = v29;
            v19 = v29;
            v26 = v28;
            // branch -> 0x8f657a10
        }
        int32_t * v30; // 0x8f657ac8_0
        int32_t * v31; // 0x8f657af4_0
        int32_t * v32; // 0x8f657b20_0
        int32_t * v33; // 0x8f657b2c_0
        int32_t v34; // 0x8f657ae8
        int32_t v35; // 0x8f657b5c
        int32_t v36; // 0x8f657b70
        int32_t str;
        uint32_t v37;
        uint32_t v38;
        bool v39; // 0x8f657a98
        uint32_t v40; // 0x8f657ae0
        int32_t v41; // 0x8f657b2c
        int32_t v42; // 0x8f657b68
        bool v43; // 0x8f657a98
        uint32_t v44; // 0x8f657a7c
        uint32_t v45; // 0x8f657a88
        int32_t v46; // 0x8f657a9c
        int32_t v47; // 0x8f657a80
        uint32_t v48; // 0x8f657a8c
        int32_t v49; // 0x8f657aa0
        if (v15 == 0) {
            // 0x8f657a18
            memset((char *)&str, 0, 64);
            snprintf((char *)&str, 64, "\nMOTO LOG Sequence: %d\n", *(int32_t *)(g30 + 16));
            int32_t v50 = &str; // 0x8f657a40
            int32_t v51 = g27; // 0x8f657a48
            g22 = v51;
            g25 = 64;
            if (generic_mmc_write_logical(g26, v51, 64, 0, v50, 0, 0, v15, v14, 0, v16, g14, 0, str, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0) != 0) {
                // 0x8f657b64
                v42 = g30;
                *(int32_t *)(v42 + 48) = 0;
                v36 = get_checksum_constprop_3(v42, g22, g25);
                g21 = v36;
                *(int32_t *)(g30 + 48) = v36;
                // branch -> 0x8f657b78
                // 0x8f657b78
                if (v4 != g19) {
                    // 0x8f657b88
                    __stack_chk_fail();
                    // branch -> 0x8f657b8c
                }
                // 0x8f657b8c
                g26 = v1;
                g27 = v2;
                g28 = v3;
                return g21;
            }
            uint32_t v52 = g26; // 0x8f657a60
            g26 = v52 + 64;
            int32_t * v53 = (int32_t *)(g30 + 24); // 0x8f657a64_0
            g27 += (int32_t)(v52 > 0xffffffbf);
            *v53 = *v53 + 64;
            v19 = g27;
            v26 = g26;
            // branch -> 0x8f657a74
            // 0x8f657a74
            v37 = (int32_t)g11;
            v44 = v37 + g13;
            g28 = v44;
            v47 = g12 + g14 + (int32_t)(v44 < v37);
            g29 = v47;
            v45 = v26 + v14;
            v48 = (int32_t)(v45 < v14) + v19;
            v43 = false;
            v39 = v48 >= v47;
            if (v48 == v47) {
                // if_8f657a94_0_true
                v43 = v45 == v44;
                v39 = v45 >= v44;
                // branch -> after_if_8f657a94_0
            }
            // after_if_8f657a94_0
            if (v43 || v39 ^ true) {
                // 0x8f657b08
                if (flush_ram_logs(v26, v19, v14, 0) != -1) {
                    // 0x8f657b20
                    v32 = (int32_t *)(g30 + 24);
                    *v32 = g31 + *v32;
                    // branch -> 0x8f657b2c
                    // 0x8f657b2c
                    v41 = g30;
                    v33 = (int32_t *)(v41 + 28);
                    *v33 = *v33 - g31;
                    *(int32_t *)(g30 + 48) = 0;
                    *(int32_t *)(g30 + 48) = get_checksum_constprop_3(v41, g22, g25);
                    v35 = generic_mmc_write_logical(g13, g14, 52, 0, g30, 0, 0, v15, v14, 0, v16, g14, 0, str, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                    g21 = v35;
                    // branch -> 0x8f657b78
                    // 0x8f657b78
                    if (v4 != g19) {
                        // 0x8f657b88
                        __stack_chk_fail();
                        // branch -> 0x8f657b8c
                    }
                    // 0x8f657b8c
                    g26 = v1;
                    g27 = v2;
                    g28 = v3;
                    return g21;
                }
            } else {
                // 0x8f657a9c
                v46 = v44 - v26;
                g28 = v46;
                v49 = v47 - v19 + (int32_t)(v44 < v26);
                g29 = v49;
                if (flush_ram_logs(v26, v19, v46, v49) != -1) {
                    // 0x8f657ac0
                    v38 = g13;
                    v30 = (int32_t *)(g30 + 24);
                    *v30 = g28 + *v30;
                    v40 = g28;
                    v34 = flush_ram_logs(v38 + 512, (int32_t)(v38 > 0xfffffdff) + g14, v14 - v40, -((g29 + (int32_t)(v14 < v40))));
                    if (v34 != -1) {
                        // 0x8f657af4
                        v31 = (int32_t *)(g30 + 24);
                        *v31 = g31 + *v31 - g28;
                        // branch -> 0x8f657b2c
                        // 0x8f657b2c
                        v41 = g30;
                        v33 = (int32_t *)(v41 + 28);
                        *v33 = *v33 - g31;
                        *(int32_t *)(g30 + 48) = 0;
                        *(int32_t *)(g30 + 48) = get_checksum_constprop_3(v41, g22, g25);
                        v35 = generic_mmc_write_logical(g13, g14, 52, 0, g30, 0, 0, v15, v14, 0, v16, g14, 0, str, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                        g21 = v35;
                        // branch -> 0x8f657b78
                        // 0x8f657b78
                        if (v4 != g19) {
                            // 0x8f657b88
                            __stack_chk_fail();
                            // branch -> 0x8f657b8c
                        }
                        // 0x8f657b8c
                        g26 = v1;
                        g27 = v2;
                        g28 = v3;
                        return g21;
                    }
                }
            }
            // 0x8f657b64
            v42 = g30;
            *(int32_t *)(v42 + 48) = 0;
            v36 = get_checksum_constprop_3(v42, g22, g25);
            g21 = v36;
            *(int32_t *)(g30 + 48) = v36;
            // branch -> 0x8f657b78
            // 0x8f657b78
            if (v4 != g19) {
                // 0x8f657b88
                __stack_chk_fail();
                // branch -> 0x8f657b8c
            }
            // 0x8f657b8c
            g26 = v1;
            g27 = v2;
            g28 = v3;
            return g21;
        }
        // 0x8f657a74
        v37 = (int32_t)g11;
        v44 = v37 + g13;
        g28 = v44;
        v47 = g12 + g14 + (int32_t)(v44 < v37);
        g29 = v47;
        v45 = v26 + v14;
        v48 = (int32_t)(v45 < v14) + v19;
        v43 = false;
        v39 = v48 >= v47;
        if (v48 == v47) {
            // if_8f657a94_0_true
            v43 = v45 == v44;
            v39 = v45 >= v44;
            // branch -> after_if_8f657a94_0
        }
        // after_if_8f657a94_0
        if (v43 || v39 ^ true) {
            // 0x8f657b08
            if (flush_ram_logs(v26, v19, v14, 0) != -1) {
                // 0x8f657b20
                v32 = (int32_t *)(g30 + 24);
                *v32 = g31 + *v32;
                // branch -> 0x8f657b2c
                // 0x8f657b2c
                v41 = g30;
                v33 = (int32_t *)(v41 + 28);
                *v33 = *v33 - g31;
                *(int32_t *)(g30 + 48) = 0;
                *(int32_t *)(g30 + 48) = get_checksum_constprop_3(v41, g22, g25);
                v35 = generic_mmc_write_logical(g13, g14, 52, 0, g30, 0, 0, v15, v14, 0, v16, g14, 0, str, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                g21 = v35;
                // branch -> 0x8f657b78
                // 0x8f657b78
                if (v4 != g19) {
                    // 0x8f657b88
                    __stack_chk_fail();
                    // branch -> 0x8f657b8c
                }
                // 0x8f657b8c
                g26 = v1;
                g27 = v2;
                g28 = v3;
                return g21;
            }
        } else {
            // 0x8f657a9c
            v46 = v44 - v26;
            g28 = v46;
            v49 = v47 - v19 + (int32_t)(v44 < v26);
            g29 = v49;
            if (flush_ram_logs(v26, v19, v46, v49) != -1) {
                // 0x8f657ac0
                v38 = g13;
                v30 = (int32_t *)(g30 + 24);
                *v30 = g28 + *v30;
                v40 = g28;
                v34 = flush_ram_logs(v38 + 512, (int32_t)(v38 > 0xfffffdff) + g14, v14 - v40, -((g29 + (int32_t)(v14 < v40))));
                if (v34 != -1) {
                    // 0x8f657af4
                    v31 = (int32_t *)(g30 + 24);
                    *v31 = g31 + *v31 - g28;
                    // branch -> 0x8f657b2c
                    // 0x8f657b2c
                    v41 = g30;
                    v33 = (int32_t *)(v41 + 28);
                    *v33 = *v33 - g31;
                    *(int32_t *)(g30 + 48) = 0;
                    *(int32_t *)(g30 + 48) = get_checksum_constprop_3(v41, g22, g25);
                    v35 = generic_mmc_write_logical(g13, g14, 52, 0, g30, 0, 0, v15, v14, 0, v16, g14, 0, str, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                    g21 = v35;
                    // branch -> 0x8f657b78
                    // 0x8f657b78
                    if (v4 != g19) {
                        // 0x8f657b88
                        __stack_chk_fail();
                        // branch -> 0x8f657b8c
                    }
                    // 0x8f657b8c
                    g26 = v1;
                    g27 = v2;
                    g28 = v3;
                    return g21;
                }
            }
        }
        // 0x8f657b64
        v42 = g30;
        *(int32_t *)(v42 + 48) = 0;
        v36 = get_checksum_constprop_3(v42, g22, g25);
        g21 = v36;
        *(int32_t *)(g30 + 48) = v36;
        // branch -> 0x8f657b78
    }
    // 0x8f657b78
    if (v4 != g19) {
        // 0x8f657b88
        __stack_chk_fail();
        // branch -> 0x8f657b8c
    }
    // 0x8f657b8c
    g26 = v1;
    g27 = v2;
    g28 = v3;
    return g21;
}

// --------------- Statically Linked Functions ----------------

// ulldiv_t __aeabi_uldivmod(unsigned long long a, unsigned long long b);
// void __stack_chk_fail(void);
// int isdigit(int c);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int snprintf(char * restrict s, size_t maxlen, const char * restrict format, ...);
// size_t strlen(const char * s);
// int strncmp(const char * s1, const char * s2, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 18
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 18:51:02
