//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ----------------- Float Types Definitions ------------------

typedef float float32_t;

// ------------------- Function Prototypes --------------------

int32_t confession_get_buffer(int32_t a1, int32_t a2, int32_t a3);
int32_t confession_get_chars(int32_t a1, int32_t a2, int32_t a3);
int32_t decode_hw_type(char * a1, int32_t a2, int32_t a3);
int32_t display_clear_screen(void);
int32_t display_draw_image(char * str, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t display_draw_image_center(char * str, uint32_t a2, uint32_t a3, int32_t a4);
int32_t display_draw_image_scr_center(char * str, uint32_t a2, uint32_t a3);
void function_8f64aacc(void);
void function_8f64ab04(int32_t a1, int32_t a2, int32_t a3);
int32_t get_hw_rev(int32_t a1, int32_t a2, int32_t a3);
int32_t get_hw_sku(int32_t a1, int32_t a2, int32_t a3);
int32_t get_last_kmsg(int32_t * a1, int32_t a2);
int32_t gfx_create_surface_from_display(int32_t * a1);
int32_t gfx_surface_destroy(char * a1, int32_t a2, int32_t a3, int32_t a4);
char * hwrev_from_utag(void);
int32_t load_and_validate_oem_image(void);
char * lz4_decode(char * a1, uint32_t a2, int32_t a3, uint32_t a4);
int32_t mcs_DER_decodeBoolean(char * a1, int16_t a2, int32_t a3);
int32_t mcs_DER_fieldLengths(int32_t a1, int16_t * a2);
int32_t mcs_memcmp(int32_t a1, int32_t a2, int32_t a3);
int32_t mcs_memset(char * a1, char a2, int32_t a3);
char * md5_process(int32_t a1, char * a2);
int32_t mdp_dma_on(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t mdp_dsi_cmd_off(int32_t a1, int32_t a2);
int32_t SecAESEncrypt(char * a1, int32_t a2, int32_t a3);
int32_t SecGetRndData(char * a1, unsigned char a2);
int32_t shutdown_modem(char * a1, int32_t a2, int32_t a3);
int32_t target_display_panel_node(char * a1, int32_t a2, int32_t a3);
int32_t type_atoi_105(char * str, int32_t a2, int32_t a3);
int32_t validate_boot_objects(int32_t a1, int32_t a2);

// --------------------- Global Variables ---------------------

int32_t g16 = 0; // LR
int32_t g17 = 0; // R0
int32_t g18 = 0; // R1
int32_t g19 = 0; // R10
int32_t g20 = 0; // R11
int32_t g21 = 0; // R2
int32_t g22 = 0; // R3
int32_t g23 = 0; // R4
int32_t g24 = 0; // R5
int32_t g25 = 0; // R6
int32_t g26 = 0; // R7
int32_t g27 = 0; // R8
int32_t g28 = 0; // R9
int32_t g1 = -0x16d2b010; // 0x8f658270
char * g2 = "\x01"; // 0x8f6a4214
char * g3 = "\x01"; // 0x8f6a4258
int32_t g4 = -1; // 0x8f6ac1f4
int32_t g5 = 2; // 0x8f6afe0c
char * g6; // 0x8f6b7990
char * g7; // 0x8f6b79a0
int32_t g8 = 0; // 0x8f6b7c38
int32_t g9 = 0; // 0x8f6e0c34
int32_t g10 = 0; // 0x8f6e0c38
int32_t g11 = 0; // 0x8f6e0c3c
char * g12; // 0x8f6e0c40
int32_t g13 = 0; // 0x8f6e12ec
int32_t g14 = 0; // 0x8f6e12f0
int32_t g15 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f64e330 - 0x8f64e71b
int32_t display_draw_image(char * str, int32_t a2, int32_t a3, int32_t a4, int32_t a5) {
    int32_t v1 = a3; // R5
    int32_t v2 = (int32_t)str; // R4
    int32_t v3 = a2; // R6
    int32_t v4 = a5; // R9
    int32_t v5;
    int32_t v6 = v5; // R8
    int32_t v7 = g15;
    if (g5 != 0) {
        // 0x8f64e3b8
        // branch -> 0x8f64e6c4
        // 0x8f64e6c4
        if (v7 != g15) {
            // 0x8f64e6d8
            __stack_chk_fail();
            // branch -> 0x8f64e6dc
        }
        // 0x8f64e6dc
        return 0;
    }
    int32_t v8 = g10; // R10
    if (g10 == 0) {
        // 0x8f64e6c0
        // branch -> 0x8f64e6c4
    } else {
        int32_t v9 = *(int32_t *)(g10 + 20); // 0x8f64e37c
        int32_t v10;
        int32_t v11;
        int32_t v12;
        if (v9 >= a3) {
            uint32_t v13 = *(int32_t *)(g10 + 16); // 0x8f64e388
            int32_t v14 = v13; // R7
            if (v13 >= a2) {
                // 0x8f64e394
                if (v5 <= v9) {
                    // 0x8f64e39c
                    if (v13 >= a5) {
                        int32_t v15 = v5 + a3; // 0x8f64e3c0
                        int32_t v16 = a5 + a2; // 0x8f64e3c4
                        if (v15 <= v9) {
                            // 0x8f64e3d0
                            if (v16 <= v13) {
                                char v17 = *(char *)&g12; // 0x8f64e3dc
                                int32_t v18 = v17; // 0x8f64e3dc
                                int32_t v19 = v18; // R3
                                int32_t v20; // 0x8f64e6b4
                                int32_t v21; // 0x8f64e6b45
                                int32_t v22; // 0x8f64e6b49
                                int32_t v23; // 0x8f64e69c
                                int32_t v24; // 0x8f64e6b0
                                int32_t v25; // R2
                                int32_t v26;
                                if (v17 != 0) {
                                    // 0x8f64e670
                                    v25 = (int32_t)"draw_image_in_landscape";
                                    print_log(-1, (int32_t)"%s: unsupported feature!\n", (int32_t)"draw_image_in_landscape", v18, v12, v11, v10, a4, 0, v7, 0, g23, g24);
                                    v22 = v10;
                                    v21 = v11;
                                    // branch -> 0x8f64e680
                                    // 0x8f64e680
                                    print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                    gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                    v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                    v26 = g11;
                                    v20 = v23;
                                    if (v26 != 0) {
                                        // 0x8f64e6b0
                                        v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                        v20 = v24;
                                        // branch -> 0x8f64e6b4
                                    }
                                    // 0x8f64e6b4
                                    display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                    // branch -> 0x8f64e6c4
                                    // 0x8f64e6c4
                                    if (v7 != g15) {
                                        // 0x8f64e6d8
                                        __stack_chk_fail();
                                        // branch -> 0x8f64e6dc
                                    }
                                    // 0x8f64e6dc
                                    return 1;
                                }
                                // 0x8f64e3e8
                                int32_t v27; // R0
                                int32_t result; // 0x8f64e6e0_2
                                int32_t v28; // bp+275
                                int32_t v29; // 0x8f64e4c043
                                int32_t v30; // 0x8f64e59c56
                                int32_t v31; // 0x8f64e614
                                int32_t v32; // 0x8f64e608
                                int32_t v33; // 0x8f64e648
                                int32_t v34; // 0x8f64e434
                                uint32_t v35; // 0x8f64e45c
                                int32_t v36; // 0x8f64e5b8
                                int32_t v37; // 0x8f64e654
                                int32_t v38; // 0x8f64e4c8
                                int32_t v39; // 0x8f64e51853
                                int32_t v40; // 0x8f64e5b4
                                int32_t v41; // 0x8f64e5b8
                                int32_t v42; // 0x8f64e5d4
                                int32_t v43; // 0x8f64e5f4
                                int32_t v44; // 0x8f64e5f8
                                int32_t v45; // 0x8f64e634
                                int32_t v46; // 0x8f64e638
                                int32_t v47; // 0x8f64e664
                                int32_t v48; // 0x8f64e4ac
                                int32_t v49; // 0x8f64e4b0
                                int32_t v50; // 0x8f64e4bc
                                int32_t v51; // 0x8f64e5a8
                                int32_t v52; // 0x8f64e5e4
                                int32_t v53; // 0x8f64e624
                                int32_t v54; // 0x8f64e60c
                                int32_t v55; // 0x8f64e64c
                                if (memcmp(str, "MotoRun", 8) == 0) {
                                    int32_t v56 = v2; // 0x8f64e404
                                    int32_t v57 = (int32_t)*(char *)(v56 + 11); // 0x8f64e404
                                    int32_t v58 = (int32_t)*(char *)(v56 + 9); // 0x8f64e40c
                                    int32_t v59 = 256 * (int32_t)*(char *)(v56 + 10); // 0x8f64e414
                                    int32_t v60 = v59 | v57; // 0x8f64e414
                                    v1 = v60;
                                    int32_t v61 = 256 * (int32_t)*(char *)(v56 + 8); // 0x8f64e420
                                    int32_t v62 = v61 | v58; // 0x8f64e420
                                    v3 = v62;
                                    if (v58 == v61) {
                                        // after_if_8f64e428_0.thread
                                        // branch -> 0x8f64e3b8
                                    } else {
                                        // after_if_8f64e428_0
                                        if (v57 != v59) {
                                            // 0x8f64e434
                                            v34 = v8;
                                            int32_t v63 = *(int32_t *)(v34 + 28); // 0x8f64e434
                                            if (v63 == 3) {
                                                // 0x8f64e454
                                                if (v60 <= v9) {
                                                    // 0x8f64e45c
                                                    v35 = v14;
                                                    if (v62 <= v35) {
                                                        int32_t v64 = v6 + v60; // 0x8f64e478
                                                        v19 = v64;
                                                        int32_t v65 = v4 + v62; // 0x8f64e47c
                                                        if (v64 <= v9) {
                                                            // 0x8f64e488
                                                            if (v65 <= v35) {
                                                                // if_8f64e48c_0_true
                                                                v2 = v56 + 12;
                                                                // branch -> 0x8f64e4a8
                                                                // 0x8f64e4a8
                                                                v48 = *(int32_t *)(v34 + 28);
                                                                v25 = v48;
                                                                v49 = *(int32_t *)v34;
                                                                if (false) {
                                                                    // 0x8f64e5b4
                                                                    v40 = v48 * v35;
                                                                    v36 = v3;
                                                                    v41 = v36 * v48;
                                                                    v8 = v41;
                                                                    v19 = a4;
                                                                    if (a4 != 0) {
                                                                        // 0x8f64e5cc
                                                                        v3 = 0;
                                                                        v42 = v1;
                                                                        v52 = ((v6 - 1 + v42) * v35 + v4) * v48 + v49;
                                                                        v14 = v52;
                                                                        if (v42 != 0) {
                                                                            v44 = v41;
                                                                            int32_t v66 = v52; // 0x8f64e5f0
                                                                            while (true) {
                                                                                // 0x8f64e5f0
                                                                                v43 = v2;
                                                                                v25 = v44;
                                                                                v2 = v43 + (v41 + 3 & -4);
                                                                                memcpy((char *)v66, (char *)v43, v44);
                                                                                v19 = v40;
                                                                                v32 = v3 + 1;
                                                                                v3 = v32;
                                                                                v54 = v14 - v40;
                                                                                v14 = v54;
                                                                                if (v32 != v1) {
                                                                                  lab_0x8f64e5f0:
                                                                                    // 0x8f64e5f0
                                                                                    v44 = v8;
                                                                                    v66 = v54;
                                                                                    // branch -> 0x8f64e5f0
                                                                                    continue;
                                                                                } else {
                                                                                    v22 = v40;
                                                                                    v21 = v9;
                                                                                }
                                                                            }
                                                                        } else {
                                                                            v22 = v40;
                                                                            v21 = v9;
                                                                        }
                                                                        // 0x8f64e680
                                                                        print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                                        gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                                                        v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                                        v26 = g11;
                                                                        v20 = v23;
                                                                        if (v26 != 0) {
                                                                            // 0x8f64e6b0
                                                                            v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                                                            v20 = v24;
                                                                            // branch -> 0x8f64e6b4
                                                                        }
                                                                        // 0x8f64e6b4
                                                                        display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                                                        // branch -> 0x8f64e6c4
                                                                        // 0x8f64e6c4
                                                                        if (v7 != g15) {
                                                                            // 0x8f64e6d8
                                                                            __stack_chk_fail();
                                                                            // branch -> 0x8f64e6dc
                                                                        }
                                                                        // 0x8f64e6dc
                                                                        return 1;
                                                                    }
                                                                    // 0x8f64e614
                                                                    v31 = v4;
                                                                    v37 = v6;
                                                                    if (v31 == 0) {
                                                                        // 0x8f64e654
                                                                        v47 = v1 * v36 * v48;
                                                                        v25 = v47;
                                                                        memcpy((char *)(v41 * v37 + v49), (char *)v2, v47);
                                                                        v22 = v40;
                                                                        v21 = v9;
                                                                        // branch -> 0x8f64e680
                                                                    } else {
                                                                        // 0x8f64e61c
                                                                        v3 = 0;
                                                                        v53 = (v37 * v35 + v31) * v48 + v49;
                                                                        v14 = v53;
                                                                        if (v1 != 0) {
                                                                            v46 = v41;
                                                                            int32_t v67 = v53; // 0x8f64e630
                                                                            while (true) {
                                                                                // 0x8f64e630
                                                                                v45 = v2;
                                                                                v25 = v46;
                                                                                v2 = v45 + v46;
                                                                                memcpy((char *)v67, (char *)v45, v46);
                                                                                v19 = v40;
                                                                                v33 = v3 + 1;
                                                                                v3 = v33;
                                                                                v55 = v14 + v40;
                                                                                v14 = v55;
                                                                                if (v33 != v1) {
                                                                                  lab_0x8f64e630:
                                                                                    // 0x8f64e630
                                                                                    v46 = v8;
                                                                                    v67 = v55;
                                                                                    // branch -> 0x8f64e630
                                                                                    continue;
                                                                                } else {
                                                                                    v22 = v40;
                                                                                    v21 = v9;
                                                                                }
                                                                            }
                                                                        } else {
                                                                            v22 = v40;
                                                                            v21 = v9;
                                                                        }
                                                                    }
                                                                    // 0x8f64e680
                                                                    print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                                    gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                                                    v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                                    v26 = g11;
                                                                    v20 = v23;
                                                                    if (v26 != 0) {
                                                                        // 0x8f64e6b0
                                                                        v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                                                        v20 = v24;
                                                                        // branch -> 0x8f64e6b4
                                                                    }
                                                                    // 0x8f64e6b4
                                                                    display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                                                    // branch -> 0x8f64e6c4
                                                                    // 0x8f64e6c4
                                                                    if (v7 != g15) {
                                                                        // 0x8f64e6d8
                                                                        __stack_chk_fail();
                                                                        // branch -> 0x8f64e6dc
                                                                    }
                                                                    // 0x8f64e6dc
                                                                    return 1;
                                                                }
                                                                // 0x8f64e4b8
                                                                v50 = (v4 + v6 * v35) * v48 + v49;
                                                                v14 = v50;
                                                                v29 = v1;
                                                                if (v29 != 0) {
                                                                    // 0x8f64e4c8
                                                                    v30 = v29;
                                                                    v39 = v50;
                                                                    v38 = v3;
                                                                    // branch -> 0x8f64e4c8
                                                                    while (true) {
                                                                        // 0x8f64e4c8
                                                                        if (v38 == 0) {
                                                                            v51 = 0;
                                                                          lab_0x8f64e598:;
                                                                            int32_t v68 = v30 - 1; // 0x8f64e59c
                                                                            int32_t v69 = *(int32_t *)(g10 + 28); // 0x8f64e5a4
                                                                            v19 = v69;
                                                                            int32_t v70 = *(int32_t *)(g10 + 16) - v51; // 0x8f64e5a8
                                                                            v25 = v70;
                                                                            int32_t v71 = v70 * v69 + v39; // 0x8f64e5ac
                                                                            v14 = v71;
                                                                            if (v68 == 0) {
                                                                                v22 = v10;
                                                                                v21 = v9;
                                                                                // break -> 0x8f64e680
                                                                                break;
                                                                            }
                                                                            v30 = v68;
                                                                            v39 = v71;
                                                                            v38 = v51;
                                                                            // continue -> 0x8f64e4c8
                                                                            continue;
                                                                        } else {
                                                                          lab_0x8f64e4d4:;
                                                                            int32_t v72 = v39; // 0x8f64e568
                                                                            uint32_t v73 = v38; // 0x8f64e56c
                                                                            int32_t v74 = v2; // 0x8f64e564
                                                                            // branch -> 0x8f64e4d4
                                                                            while (true) {
                                                                                char v75 = *(char *)(v74 + 1); // 0x8f64e4d8
                                                                                uint32_t v76 = (int32_t)v75 | 256 * (int32_t)*(char *)v74; // 0x8f64e4dc
                                                                                v4 = v76;
                                                                                int32_t v77; // 0x8f64e4d449
                                                                                int32_t v78; // 0x8f64e58c
                                                                                if ((v76 & 0x8000) == 0) {
                                                                                    // 0x8f64e548
                                                                                    if (v73 < v76) {
                                                                                        // after_if_8f64e554_0.thread
                                                                                        // branch -> 0x8f64e3b8
                                                                                    } else {
                                                                                        // after_if_8f64e554_0
                                                                                        if ((v76 > 1 ? 0 : 1 - v76) == 0) {
                                                                                            int32_t v79 = v74 + 2; // 0x8f64e564
                                                                                            v6 = v73 - v76;
                                                                                            int32_t v80 = *(int32_t *)(g10 + 28); // 0x8f64e574
                                                                                            memcpy((char *)v72, (char *)v79, v80 * v76);
                                                                                            int32_t v81 = v4 * *(int32_t *)(g10 + 28); // 0x8f64e588
                                                                                            v78 = v14 + v81;
                                                                                            v14 = v78;
                                                                                            v77 = v79 + v81;
                                                                                            // branch -> 0x8f64e4cc
                                                                                          lab_0x8f64e4cc_2:;
                                                                                            int32_t v82 = v6;
                                                                                            if (v82 == 0) {
                                                                                                // break -> 0x8f64e4cc
                                                                                                break;
                                                                                            }
                                                                                            v72 = v78;
                                                                                            v73 = v82;
                                                                                            v74 = v77;
                                                                                            // continue -> 0x8f64e4d4
                                                                                            continue;
                                                                                        }
                                                                                    }
                                                                                    // 0x8f64e3b8
                                                                                    // branch -> 0x8f64e6c4
                                                                                    // 0x8f64e6c4
                                                                                    if (v7 != g15) {
                                                                                        // 0x8f64e6d8
                                                                                        __stack_chk_fail();
                                                                                        // branch -> 0x8f64e6dc
                                                                                    }
                                                                                    // 0x8f64e6dc
                                                                                    return 0;
                                                                                }
                                                                                uint32_t v83 = v76 % 0x8000; // 0x8f64e4e8
                                                                                v4 = v83;
                                                                                if (v73 < v83) {
                                                                                    // after_if_8f64e4f8_0.thread
                                                                                    // branch -> 0x8f64e3b8
                                                                                } else {
                                                                                    // after_if_8f64e4f8_0
                                                                                    if ((v83 > 1 ? 0 : 1 - v83) == 0) {
                                                                                        char v84 = *(char *)(v74 + 2); // 0x8f64e504
                                                                                        v27 = v84;
                                                                                        int32_t v85 = v74 + 5; // 0x8f64e508
                                                                                        int32_t v86 = (int32_t)*(char *)(v74 + 3); // R12
                                                                                        v6 = v73 - v83;
                                                                                        v2 = (int32_t)*(char *)(v74 + 4);
                                                                                        v19 = v72;
                                                                                        bool v87 = v83 != 0; // flagc
                                                                                        v25 = v83 - 1;
                                                                                        int32_t v88 = v72; // 0x8f64e540
                                                                                        int32_t v89; // 0x8f64e540
                                                                                        if (v83 != 0) {
                                                                                            // after_if_8f64e524_0.preheader
                                                                                            *(char *)v72 = v84;
                                                                                            int32_t v90;
                                                                                            if (v87) {
                                                                                                while (true) {
                                                                                                    int32_t v91 = v19; // 0x8f64e528
                                                                                                    v19 = v91 + 3;
                                                                                                    *(char *)(v91 + 1) = (char)v86;
                                                                                                    if (v87) {
                                                                                                        // after_if_8f64e530_0
                                                                                                        *(char *)(v19 - 1) = (char)v2;
                                                                                                        if (v87) {
                                                                                                            int32_t v92 = v25;
                                                                                                            v87 = v92 != 0;
                                                                                                            v25 = v92 - 1;
                                                                                                            if (v92 != 0) {
                                                                                                                // 0x8f64e520
                                                                                                                *(char *)v19 = (char)v27;
                                                                                                                if (!v87) {
                                                                                                                    // break -> 0x8f64e538
                                                                                                                    break;
                                                                                                                }
                                                                                                                // continue -> after_if_8f64e52c_0
                                                                                                                continue;
                                                                                                            }
                                                                                                        }
                                                                                                    }
                                                                                                }
                                                                                                // 0x8f64e538
                                                                                                // branch -> 0x8f64e538
                                                                                              lab_0x8f64e538:
                                                                                                // 0x8f64e538
                                                                                                v89 = v14 + 3 * v90;
                                                                                                v14 = v89;
                                                                                                v78 = v89;
                                                                                                v77 = v85;
                                                                                                // branch -> 0x8f64e4cc
                                                                                                goto lab_0x8f64e4cc_2;
                                                                                            }
                                                                                            // 0x8f64e538
                                                                                            v90 = v4;
                                                                                            // branch -> 0x8f64e538
                                                                                            goto lab_0x8f64e538;
                                                                                        }
                                                                                        // 0x8f64e538
                                                                                        v89 = v88;
                                                                                        v14 = v89;
                                                                                        v78 = v89;
                                                                                        v77 = v85;
                                                                                        // branch -> 0x8f64e4cc
                                                                                        goto lab_0x8f64e4cc_2;
                                                                                    }
                                                                                }
                                                                                // 0x8f64e3b8
                                                                                // branch -> 0x8f64e6c4
                                                                                // 0x8f64e6c4
                                                                                if (v7 != g15) {
                                                                                    // 0x8f64e6d8
                                                                                    __stack_chk_fail();
                                                                                    // branch -> 0x8f64e6dc
                                                                                }
                                                                                // 0x8f64e6dc
                                                                                return 0;
                                                                            }
                                                                        }
                                                                        // 0x8f64e6c4
                                                                        if (v7 != g15) {
                                                                            // 0x8f64e6d8
                                                                            __stack_chk_fail();
                                                                            result = v27;
                                                                            // branch -> 0x8f64e6dc
                                                                        } else {
                                                                            result = v28;
                                                                        }
                                                                        // 0x8f64e6dc
                                                                        return result;
                                                                    }
                                                                } else {
                                                                    v22 = v10;
                                                                    v21 = v9;
                                                                }
                                                                // 0x8f64e680
                                                                print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                                gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                                                v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                                v26 = g11;
                                                                v20 = v23;
                                                                if (v26 != 0) {
                                                                    // 0x8f64e6b0
                                                                    v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                                                    v20 = v24;
                                                                    // branch -> 0x8f64e6b4
                                                                }
                                                                // 0x8f64e6b4
                                                                display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                                                // branch -> 0x8f64e6c4
                                                                // 0x8f64e6c4
                                                                if (v7 != g15) {
                                                                    // 0x8f64e6d8
                                                                    __stack_chk_fail();
                                                                    // branch -> 0x8f64e6dc
                                                                }
                                                                // 0x8f64e6dc
                                                                return 1;
                                                            }
                                                        }
                                                        // 0x8f64e498
                                                        // branch -> 0x8f64e3b4
                                                        // 0x8f64e3b4
                                                        print_log(-1, (int32_t)"Part of image (%d x %d) is out of screen\n", v65, v64, v12, v9, v10, a4, 0, v7, 0, g23, g24);
                                                        // branch -> 0x8f64e3b8
                                                        // 0x8f64e3b8
                                                        // branch -> 0x8f64e6c4
                                                        // 0x8f64e6c4
                                                        if (v7 != g15) {
                                                            // 0x8f64e6d8
                                                            __stack_chk_fail();
                                                            // branch -> 0x8f64e6dc
                                                        }
                                                        // 0x8f64e6dc
                                                        return 0;
                                                    }
                                                }
                                                // 0x8f64e464
                                                // branch -> 0x8f64e3b4
                                                // 0x8f64e3b4
                                                print_log(-1, (int32_t)"Image (%d x %d) is too large for screen\n", v62, v60, v12, v9, v10, a4, 0, v7, 0, g23, g24);
                                                // branch -> 0x8f64e3b8
                                            } else {
                                                // 0x8f64e440
                                                print_log(-1, (int32_t)"Invalid logo pixel format %d\n", 8 * v63, 0, v12, v9, v10, a4, 0, v7, 0, g23, g24);
                                                // branch -> 0x8f64e3b8
                                            }
                                            // 0x8f64e3b8
                                            // branch -> 0x8f64e6c4
                                            // 0x8f64e6c4
                                            if (v7 != g15) {
                                                // 0x8f64e6d8
                                                __stack_chk_fail();
                                                // branch -> 0x8f64e6dc
                                            }
                                            // 0x8f64e6dc
                                            return 0;
                                        }
                                    }
                                    // 0x8f64e3b8
                                    v27 = 0;
                                    v28 = 0;
                                    // branch -> 0x8f64e6c4
                                } else {
                                    // 0x8f64e3e8
                                    v35 = v14;
                                    v34 = v8;
                                    // branch -> 0x8f64e4a8
                                    // 0x8f64e4a8
                                    v48 = *(int32_t *)(v34 + 28);
                                    v25 = v48;
                                    v49 = *(int32_t *)v34;
                                    // 0x8f64e5b4
                                    v40 = v48 * v35;
                                    v36 = v3;
                                    v41 = v36 * v48;
                                    v8 = v41;
                                    v19 = a4;
                                    if (a4 != 0) {
                                        // 0x8f64e5cc
                                        v42 = v1;
                                        v52 = ((v6 - 1 + v42) * v35 + v4) * v48 + v49;
                                        if (v42 != 0) {
                                            v44 = v41;
                                            while (true) {
                                                // 0x8f64e5f0
                                                v43 = v2;
                                                v25 = v44;
                                                v2 = v43 + (v41 + 3 & -4);
                                                memcpy((char *)v52, (char *)v43, v44);
                                                v19 = v40;
                                                v32 = 1;
                                                v3 = v32;
                                                v54 = v52 - v40;
                                                v14 = v54;
                                                if (v32 != v1) {
                                                    goto lab_0x8f64e5f0;
                                                }
                                                v22 = v40;
                                                v21 = v9;
                                                // 0x8f64e680
                                                print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                                v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                v26 = g11;
                                                v20 = v23;
                                                if (v26 != 0) {
                                                    // 0x8f64e6b0
                                                    v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                                    v20 = v24;
                                                    // branch -> 0x8f64e6b4
                                                }
                                                // 0x8f64e6b4
                                                display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                                // branch -> 0x8f64e6c4
                                                // 0x8f64e6c4
                                                if (v7 != g15) {
                                                    // 0x8f64e6d8
                                                    __stack_chk_fail();
                                                    // branch -> 0x8f64e6dc
                                                }
                                                // 0x8f64e6dc
                                                return 1;
                                            }
                                        } else {
                                            v22 = v40;
                                            v21 = v9;
                                        }
                                        // 0x8f64e680
                                        print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                        gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                        v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                        v26 = g11;
                                        v20 = v23;
                                        if (v26 != 0) {
                                            // 0x8f64e6b0
                                            v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                            v20 = v24;
                                            // branch -> 0x8f64e6b4
                                        }
                                        // 0x8f64e6b4
                                        display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                        // branch -> 0x8f64e6c4
                                        // 0x8f64e6c4
                                        if (v7 != g15) {
                                            // 0x8f64e6d8
                                            __stack_chk_fail();
                                            // branch -> 0x8f64e6dc
                                        }
                                        // 0x8f64e6dc
                                        return 1;
                                    }
                                    // 0x8f64e614
                                    v31 = v4;
                                    v37 = v6;
                                    if (v31 == 0) {
                                        // 0x8f64e654
                                        v47 = v1 * v36 * v48;
                                        v25 = v47;
                                        memcpy((char *)(v41 * v37 + v49), (char *)v2, v47);
                                        v22 = v40;
                                        v21 = v9;
                                        // branch -> 0x8f64e680
                                    } else {
                                        // 0x8f64e61c
                                        v53 = (v37 * v35 + v31) * v48 + v49;
                                        if (v1 != 0) {
                                            v46 = v41;
                                            while (true) {
                                                // 0x8f64e630
                                                v45 = v2;
                                                v25 = v46;
                                                v2 = v45 + v46;
                                                memcpy((char *)v53, (char *)v45, v46);
                                                v19 = v40;
                                                v33 = 1;
                                                v3 = v33;
                                                v55 = v53 + v40;
                                                v14 = v55;
                                                if (v33 != v1) {
                                                    goto lab_0x8f64e630;
                                                }
                                                v22 = v40;
                                                v21 = v9;
                                                // 0x8f64e680
                                                print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                                v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                                v26 = g11;
                                                v20 = v23;
                                                if (v26 != 0) {
                                                    // 0x8f64e6b0
                                                    v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                                    v20 = v24;
                                                    // branch -> 0x8f64e6b4
                                                }
                                                // 0x8f64e6b4
                                                display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                                // branch -> 0x8f64e6c4
                                                // 0x8f64e6c4
                                                if (v7 != g15) {
                                                    // 0x8f64e6d8
                                                    __stack_chk_fail();
                                                    // branch -> 0x8f64e6dc
                                                }
                                                // 0x8f64e6dc
                                                return 1;
                                            }
                                        } else {
                                            v22 = v40;
                                            v21 = v9;
                                        }
                                    }
                                    // 0x8f64e680
                                    print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                    gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                    v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                    v26 = g11;
                                    v20 = v23;
                                    if (v26 != 0) {
                                        // 0x8f64e6b0
                                        v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                        v20 = v24;
                                        // branch -> 0x8f64e6b4
                                    }
                                    // 0x8f64e6b4
                                    display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                    // branch -> 0x8f64e6c4
                                    // 0x8f64e6c4
                                    if (v7 != g15) {
                                        // 0x8f64e6d8
                                        __stack_chk_fail();
                                        // branch -> 0x8f64e6dc
                                    }
                                    // 0x8f64e6dc
                                    return 1;
                                    // 0x8f64e4b8
                                    v50 = (v4 + v6 * v35) * v48 + v49;
                                    v14 = v50;
                                    v29 = v1;
                                    if (v29 != 0) {
                                        // 0x8f64e4c8
                                        v30 = v29;
                                        v39 = v50;
                                        v38 = v3;
                                        // branch -> 0x8f64e4c8
                                        while (true) {
                                            // 0x8f64e4c8
                                            if (v38 == 0) {
                                                v51 = 0;
                                                goto lab_0x8f64e598;
                                            }
                                            goto lab_0x8f64e4d4;
                                        }
                                    } else {
                                        v22 = v10;
                                        v21 = v9;
                                    }
                                    // 0x8f64e680
                                    print_log(2, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                    gfx_flush(g10, (int32_t)"flush surface...\n", v25, v19, v12, v21, v22);
                                    v23 = print_log(2, (int32_t)"flush surface end\n", v25, v19, v12, v21, v22, a4, 0, v7, 0, g23, g24);
                                    v26 = g11;
                                    v20 = v23;
                                    if (v26 != 0) {
                                        // 0x8f64e6b0
                                        v24 = mipi_cmd_trigger(v23, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22, a4);
                                        v20 = v24;
                                        // branch -> 0x8f64e6b4
                                    }
                                    // 0x8f64e6b4
                                    display_render_done(v20, (int32_t)"flush surface end\n", v25, v26, v12, v21, v22);
                                    v27 = 1;
                                    v28 = 1;
                                    // branch -> 0x8f64e6c4
                                }
                                // 0x8f64e6c4
                                if (v7 != g15) {
                                    // 0x8f64e6d8
                                    __stack_chk_fail();
                                    result = v27;
                                    // branch -> 0x8f64e6dc
                                } else {
                                    result = v28;
                                }
                                // 0x8f64e6dc
                                return result;
                            }
                        }
                        // 0x8f64e498
                        // branch -> 0x8f64e3b4
                        // 0x8f64e3b4
                        print_log(-1, (int32_t)"Part of image (%d x %d) is out of screen\n", v16, v15, v12, v11, v10, a4, 0, v7, 0, g23, g24);
                        // branch -> 0x8f64e3b8
                        // 0x8f64e3b8
                        // branch -> 0x8f64e6c4
                        // 0x8f64e6c4
                        if (v7 != g15) {
                            // 0x8f64e6d8
                            __stack_chk_fail();
                            // branch -> 0x8f64e6dc
                        }
                        // 0x8f64e6dc
                        return 0;
                    }
                }
                // 0x8f64e3a4
                // branch -> 0x8f64e3b4
                // 0x8f64e3b4
                print_log(-1, (int32_t)"Coordinate (%d x %d) is out of screen\n", a5, v5, v12, v11, v10, a4, 0, v7, 0, g23, g24);
                // branch -> 0x8f64e3b8
                // 0x8f64e3b8
                // branch -> 0x8f64e6c4
                // 0x8f64e6c4
                if (v7 != g15) {
                    // 0x8f64e6d8
                    __stack_chk_fail();
                    // branch -> 0x8f64e6dc
                }
                // 0x8f64e6dc
                return 0;
            }
        }
        // 0x8f64e464
        // branch -> 0x8f64e3b4
        // 0x8f64e3b4
        print_log(-1, (int32_t)"Image (%d x %d) is too large for screen\n", a2, a3, v12, v11, v10, a4, 0, v7, 0, g23, g24);
        // branch -> 0x8f64e3b8
        // 0x8f64e3b8
        // branch -> 0x8f64e6c4
    }
    // 0x8f64e6c4
    if (v7 != g15) {
        // 0x8f64e6d8
        __stack_chk_fail();
        // branch -> 0x8f64e6dc
    }
    // 0x8f64e6dc
    return 0;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// int atoi(const char * nptr);
// void free(void * ptr);
// int memcmp(const void * s1, const void * s2, size_t n);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int strcmp(const char * s1, const char * s2);
// size_t strlen(const char * s);

// --------------- Instruction-Idiom Functions ----------------

// float32_t fabsf(float32_t a1);
// int32_t llvm_bswap_i32(int32_t a1);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 30
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 19:12:15
