//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <ctype.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t _fdt_add_property(int32_t a1, int32_t a2, char * a3, int32_t a4);
int32_t _fdt_blocks_misordered(int32_t a1, int32_t a2, int32_t a3);
int32_t _fdt_splice(void);
int32_t _fdt_splice_struct(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t _nextprop(int32_t a1, int32_t result2);
int32_t copyrect24(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
int32_t fdt32_to_cpu_100(int32_t a1, int32_t a2, int32_t a3);
int32_t fdt32_to_cpu_101(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t fdt32_to_cpu_99(int32_t a1, int32_t a2, int32_t a3);
int32_t fdt64_to_cpu(int32_t a1, int32_t a2);
int32_t fdt_check_header(int32_t * a1, int32_t a2, int32_t a3);
int32_t fdt_string(int32_t a1, int32_t a2);
int32_t fillrect24(int32_t * a1, int32_t a2, int32_t a3, uint32_t a4, int32_t a5);
void function_8f649c50(char * a1, int32_t a2);
void function_8f64a450(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t gfx_fillrect(int32_t a1, uint32_t a2, uint32_t a3, int32_t a4, int32_t a5);
int32_t heap_alloc(uint32_t a1, uint32_t a2);
int32_t heap_insert_free_chunk(int32_t * a1, int32_t a2);
int32_t hexval(int32_t a1);
int32_t longlong_to_string_constprop_0(int32_t a1, int32_t a2, int64_t a3, int32_t a4);
int32_t putpixel16(int32_t * a1, int32_t a2, int32_t a3, uint32_t a4);
int32_t putpixel24(int32_t * a1, uint32_t a2, uint32_t a3);

// --------------------- Global Variables ---------------------

int32_t g5 = 0; // LR
int32_t g6 = 0; // R0
int32_t g7 = 0; // R1
int32_t g8 = 0; // R10
int32_t g9 = 0; // R11
int32_t g10 = 0; // R2
int32_t g11 = 0; // R3
int32_t g12 = 0; // R4
int32_t g13 = 0; // R5
int32_t g14 = 0; // R6
int32_t g15 = 0; // R7
int32_t g16 = 0; // R8
int32_t g17 = 0; // R9
int32_t g1 = 1; // 0x8f6ac0f0
int32_t g2 = 0; // 0x8f6e0bf0
int32_t g3 = 0; // 0x8f6e0bf4
int32_t g4 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f64c99c - 0x8f64cbcb
int32_t _fdt_add_property(int32_t a1, int32_t a2, char * a3, int32_t a4) {
    int32_t v1 = (int32_t)a3;
    int32_t v2 = g12; // 0x8f64c99c
    int32_t v3 = g13; // 0x8f64c99c
    int32_t v4 = g14; // 0x8f64c99c
    int32_t v5 = g15; // 0x8f64c99c
    g17 = a4;
    g12 = a1;
    g16 = a2;
    g9 = v1;
    int32_t v6;
    g8 = v6;
    int32_t v7 = g4;
    int32_t v8;
    int32_t result = _fdt_check_node_offset(a1, a2, v1, v7, v8); // 0x8f64c9c4
    g15 = result;
    if (result < 0) {
        // if_8f64c9cc_0_true
        // branch -> 0x8f64cba0
        // 0x8f64cba0
        if (v7 != g4) {
            // 0x8f64cbb8
            __stack_chk_fail();
            // branch -> 0x8f64cbbc
        }
        // 0x8f64cbbc
        return result;
    }
    // 0x8f64c9d4
    g13 = fdt32_to_cpu_101(*(int32_t *)(g12 + 12), a2, v1, v7, v8);
    g14 = strlen((char *)g9) + 1;
    int32_t v9 = fdt32_to_cpu_101(*(int32_t *)(g12 + 32), a2, v1, v7, v8); // 0x8f64c9f0
    g10 = 0;
    g11 = g14;
    int32_t v10 = g12; // 0x8f64ca04
    int32_t v11 = g13 + v9 + v10; // 0x8f64ca04
    g7 = v11;
    g6 = v10;
    int32_t v12 = _fdt_splice(); // 0x8f64ca10
    int32_t v13 = v9; // 0x8f64cb943
    int32_t result2 = v12;
    if (v12 == 0) {
        int32_t v14 = g12; // 0x8f64ca24
        int32_t v15 = v14 + g13; // 0x8f64ca24
        int32_t v16 = *(int32_t *)(v14 + 32); // 0x8f64ca28
        int32_t v17 = v15 + v9; // R5
        int32_t v18 = fdt32_to_cpu_101(g14 + fdt32_to_cpu_101(v16, v11, 0, v15, v15), v11, 0, v15, v15); // 0x8f64ca3c
        *(int32_t *)(g12 + 32) = v18;
        memcpy((char *)v17, (char *)g9, g14);
        v13 = v15;
        result2 = v17 - v15;
        // branch -> 0x8f64ca5c
    }
    // 0x8f64ca5c
    g13 = result2;
    if (result2 < 0) {
        // 0x8f64cba0
        if (v7 != g4) {
            // 0x8f64cbb8
            __stack_chk_fail();
            // branch -> 0x8f64cbbc
        }
        // 0x8f64cbbc
        return result2;
    }
    int32_t v19 = g16; // 0x8f64ca64
    int32_t v20;
    int32_t v21 = &v20; // 0x8f64ca70_0
    int32_t v22;
    int32_t v23 = fdt_get_property(g12, v19, (int32_t)"mmi,reserve", v21, v13, v22, v20, v7, 0, v2, v3, v4, v5); // 0x8f64ca74
    int32_t v24 = g17 + 3; // 0x8f64ca78
    g9 = v24;
    g16 = v23;
    int32_t result3; // 0x8f64cb68
    if (v23 == 0) {
        int32_t v25 = *(int32_t *)(g12 + 8); // 0x8f64cb44
        int32_t v26 = g9 + 12 & -4; // 0x8f64cb54
        int32_t v27 = g12; // 0x8f64cb5c
        int32_t v28 = g15 + fdt32_to_cpu_101(v25, v19, (int32_t)"mmi,reserve", v21, v13) + v27; // 0x8f64cb5c
        *(int32_t *)g8 = v28;
        result3 = _fdt_splice_struct(v27, v28, g16, v26);
        if (result3 == 0) {
            int32_t v29 = *(int32_t *)g8; // R4
            *(int32_t *)v29 = fdt32_to_cpu_101(3, v28, g16, v26, v13);
            int32_t v30 = fdt32_to_cpu_101(g13, v28, g16, v26, v13); // 0x8f64cb88
            *(int32_t *)(v29 + 8) = v30;
            int32_t v31 = fdt32_to_cpu_101(g17, v28, g16, v26, v13); // 0x8f64cb94
            *(int32_t *)(v29 + 4) = v31;
            // branch -> 0x8f64cb9c
        }
        // branch -> 0x8f64cba0
    } else {
        int32_t v32 = v24 & -4; // 0x8f64ca84
        int32_t v33 = v32 + 12; // 0x8f64ca8c
        g14 = v33;
        int32_t v34; // R8
        int32_t v35; // 0x8f64cb04
        int32_t v36; // 0x8f64cb0c
        int32_t v37; // 0x8f64cb14
        if (v20 < v33) {
            int32_t v38 = v32 + 267 & -256; // 0x8f64cac8
            g9 = v38;
            int32_t v39 = v23 + 12; // 0x8f64cad0
            int32_t v40 = _fdt_splice_struct(g12, v39, v20 + 3 & -4, v38); // 0x8f64cadc
            if (v40 == 0) {
                int32_t v41 = fdt32_to_cpu_101(g9 - g14, v39, g10, g11, v13); // 0x8f64caf0
                g7 = v32;
                *(int32_t *)(g16 + 4) = v41;
                // branch -> 0x8f64cb04
                // 0x8f64cb04
                v35 = *(int32_t *)(g12 + 8);
                v36 = g9 - v32 + g15 + fdt32_to_cpu_101(v35, g7, g10, g11, v13);
                v37 = g12 + v36;
                v34 = v37;
                *(int32_t *)g8 = v37;
                *(int32_t *)(v36 + g12) = fdt32_to_cpu_101(3, g7, g10, g11, v13);
                *(int32_t *)(v34 + 8) = fdt32_to_cpu_101(g13, g7, g10, g11, v13);
                *(int32_t *)(v34 + 4) = fdt32_to_cpu_101(g17, g7, g10, g11, v13);
                result3 = 0;
                // branch -> 0x8f64cba0
            } else {
                // if_8f64cae4_0_true
                result3 = v40;
                // branch -> 0x8f64cba0
            }
            // 0x8f64cba0
            if (v7 != g4) {
                // 0x8f64cbb8
                __stack_chk_fail();
                // branch -> 0x8f64cbbc
            }
            // 0x8f64cbbc
            return result3;
        }
        int32_t v42 = fdt32_to_cpu_101(v20 - v33, v19, v20, v21, v20); // 0x8f64caa4
        int32_t v43 = v20 + 12; // 0x8f64caac
        g10 = v43;
        *(int32_t *)(g16 + 4) = v42;
        v13 = v20;
        // branch -> 0x8f64cb04
        // 0x8f64cb04
        v35 = *(int32_t *)(g12 + 8);
        v36 = v43 - g14 + g15 + fdt32_to_cpu_101(v35, g7, g10, g11, v13);
        v37 = g12 + v36;
        v34 = v37;
        *(int32_t *)g8 = v37;
        *(int32_t *)(v36 + g12) = fdt32_to_cpu_101(3, g7, g10, g11, v13);
        *(int32_t *)(v34 + 8) = fdt32_to_cpu_101(g13, g7, g10, g11, v13);
        *(int32_t *)(v34 + 4) = fdt32_to_cpu_101(g17, g7, g10, g11, v13);
        result3 = 0;
        // branch -> 0x8f64cba0
    }
    // 0x8f64cba0
    if (v7 != g4) {
        // 0x8f64cbb8
        __stack_chk_fail();
        // branch -> 0x8f64cbbc
    }
    // 0x8f64cbbc
    return result3;
}

// --------------- Statically Linked Functions ----------------

// ulldiv_t __aeabi_uldivmod(unsigned long long a, unsigned long long b);
// void __stack_chk_fail(void);
// int isdigit(int c);
// int isxdigit(int c);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 22
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 18:49:11
