//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t _fdt_add_property(int32_t a1, int32_t a2, char * a3, int32_t a4);
int32_t _fdt_packblocks(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t _fdt_rw_check_header(void);
int32_t blink_callback(int32_t a1, int32_t a2);
int32_t build_sig_for_all(char * str, int32_t (*a2)(int32_t, int32_t), int32_t a3);
int32_t cmd_line_parse(int32_t a1, int32_t a2, int32_t a3);
int32_t cmd_overlay_command_tokens(char * str6, int32_t a2);
int32_t cmd_token_append(int32_t * a1, int32_t * a2, int32_t a3);
int32_t cmd_token_free(char * a1, int32_t a2);
char * collect_desc(int32_t * str2);
int32_t display_auto_detect(int32_t a1, int32_t a2, int32_t a3);
int32_t display_draw_text_with_color(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8);
int32_t display_render_done(int32_t a1, int32_t a2);
int32_t draw_runlength_image(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
int32_t draw_text_in_landscape(char * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t draw_text_in_portrait(char * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t fdt_reserveprop(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t generic_mmc_erase_legacy(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t generic_mmc_erase_logical(int64_t a1, int32_t a2, uint32_t a3, int32_t a4);
int32_t led_on(char a1, int32_t a2, int32_t a3);
int32_t lstrdup(char * str);
int32_t strtok_r_q_constprop_3(void);

// --------------------- Global Variables ---------------------

int32_t g26 = 0; // LR
int32_t g27 = 0; // R0
int32_t g28 = 0; // R1
int32_t g29 = 0; // R10
int32_t g30 = 0; // R11
int32_t g31 = 0; // R12
int32_t g32 = 0; // R2
int32_t g33 = 0; // R3
int32_t g34 = 0; // R4
int32_t g35 = 0; // R5
int32_t g36 = 0; // R6
int32_t g37 = 0; // R7
int32_t g38 = 0; // R8
int32_t g39 = 0; // R9
bool g1 = false; // flagc
int32_t g2 = 0xa092000; // 0x8f6826e4
char * g3; // 0x8f6a4e20
int32_t g4 = 2; // 0x8f6afe0c
char * g5 = "\x01"; // 0x8f6afe10
int32_t g6 = 0; // 0x8f6e0bfc
int32_t g7 = 0; // 0x8f6e0c00
int32_t g8 = 0; // 0x8f6e0c08
int32_t g9 = 0; // 0x8f6e0c2c
int32_t g10 = 0; // 0x8f6e0c30
int32_t g11 = 0; // 0x8f6e0c38
char * g12; // 0x8f6e0c40
char * g13; // 0x8f6e0c48
char g14 = 0; // 0x8f6e0c49
int32_t g15 = 0; // 0x8f6e0c68
int32_t g16 = 0; // 0x8f6e0c6c
char * g17; // 0x8f6e1000
int32_t g18 = 0; // 0x8f6e1200
char * g19; // 0x8f6e122c
int32_t g20 = 0; // 0x8f6e1253
int32_t g21 = 0; // 0x8f6e1254
int32_t g22 = 0; // 0x8f6e12dc
char * g23; // 0x8f6e12e4
char * g24; // 0x8f7112f4
int32_t g25 = 0; // 0x8f7125ec

// ------------------------ Functions -------------------------

// Address range: 0x8f64d664 - 0x8f64d8ff
int32_t draw_runlength_image(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6) {
    char * v1 = g24;
    int32_t v2 = g11;
    int32_t v3 = *(int32_t *)v2; // 0x8f64d69c
    int32_t v4 = *(int32_t *)(v2 + 28); // 0x8f64d6a4
    int32_t v5 = *(int32_t *)(v2 + 20); // 0x8f64d6a8
    int32_t v6 = v4 * (*(int32_t *)(v2 + 16) * a5 + a4) + v3; // 0x8f64d6b0
    if (v5 != 0) {
        int32_t v7 = (int32_t)a1; // 0x8f64d6dc25
        while (true) {
            // after_if_8f64d6bc_0
            if (a3 == 0) {
                // 0x8f64d8c4
                // branch -> 0x8f64d8d8
                // 0x8f64d8d8
                if (v1 != g24) {
                    // 0x8f64d8ec
                    __stack_chk_fail();
                    // branch -> 0x8f64d8f0
                }
                // 0x8f64d8f0
                return 1;
            }
            int32_t v8 = *(int32_t *)(g11 + 16); // R4
            int32_t v9; // R0
            int32_t v10;
            if (a2 == 0) {
                int32_t v11 = v10; // 0x8f64d890
                int32_t v12 = v6; // 0x8f64d8b8
              lab_0x8f64d88c:;
                // 0x8f64d88c
                int32_t v13; // 0x8f64d88c55
                int32_t v14; // 0x8f64d8a43
                int32_t v15; // 0x8f64d8b8
                if (v10 == 0) {
                    int32_t v16 = g11;
                    uint32_t v17 = *(int32_t *)(v16 + 16); // 0x8f64d8a0
                    int32_t v18 = v5 - 1; // 0x8f64d8a4
                    if (v17 > a2) {
                        // if_8f64d8b0_0_true
                        v15 = *(int32_t *)(v16 + 28) * (v17 - a2) + v12;
                        v13 = 0;
                        v14 = v18;
                        // branch -> 0x8f64d8bc
                    } else {
                        v13 = 0;
                        v15 = v12;
                        v14 = v18;
                    }
                } else {
                    // after_if_8f64d890_0
                    v13 = v11 - 1;
                    v15 = v12;
                    v14 = v5;
                    // branch -> 0x8f64d8bc
                }
                // 0x8f64d8bc
                if (v14 == 0) {
                    // break -> 0x8f64d8c4
                    break;
                }
                v10 = v13;
                v6 = v15;
                a3--;
                v5 = v14;
                // continue -> after_if_8f64d6bc_0
                continue;
            } else {
                while (true) {
                    char v19 = *(char *)(v7 + 1); // 0x8f64d6e0
                    uint32_t v20 = (int32_t)v19 | 256 * (int32_t)*(char *)v7; // 0x8f64d6e4
                    int32_t v21; // R12
                    int32_t v22; // R5
                    int32_t v23; // R8
                    int32_t v24; // 0x8f64d6d4
                    int32_t v25; // 0x8f64d74c37
                    int32_t v26;
                    int32_t v27; // 0x8f64d884
                    int32_t v28; // 0x8f64d71c28
                    int32_t v29; // 0x8f64d71c30
                    if ((v20 & 0x8000) == 0) {
                        // 0x8f64d7cc
                        if (a2 < v20) {
                            // after_if_8f64d7d8_0.thread
                            // branch -> 0x8f64d8d4
                        } else {
                            // after_if_8f64d7d8_0
                            if ((v20 > 1 ? 0 : 1 - v20) == 0) {
                                int32_t v30 = v7 + 2; // 0x8f64d7e8
                                v23 = a2 - v20;
                                int32_t v31 = v30; // 0x8f64d878
                                int32_t v32 = v20; // 0x8f64d878
                                v28 = a6;
                                int32_t v33 = v6; // 0x8f64d74c32
                                if (v10 == 0) {
                                    // 0x8f64d7f4
                                    if (v20 > a6) {
                                        // if_8f64d7f8_0_true
                                        // branch -> 0x8f64d870
                                    } else {
                                        uint32_t v34 = v8; // 0x8f64d804
                                        int32_t v35 = v20 - a6; // 0x8f64d808
                                        v22 = v35;
                                        int32_t v36 = *(int32_t *)(g11 + 28); // 0x8f64d80c
                                        int32_t v37 = v36 * a6 + v30; // 0x8f64d810
                                        if (v34 == 0) {
                                            // after_if_8f64d814_0
                                            v32 = v35;
                                            v28 = 0;
                                            v33 = v6;
                                            // branch -> 0x8f64d870
                                        } else {
                                            char * v38 = (char *)v6;
                                            char * v39 = (char *)v37;
                                            int32_t v40; // 0x8f64d844
                                            if (v34 > v35) {
                                                // 0x8f64d82c
                                                memcpy(v38, v39, v36 * v35);
                                                int32_t v41 = v22; // 0x8f64d83c
                                                v8 -= v41;
                                                v40 = v6 + *(int32_t *)(g11 + 28) * v41;
                                                // branch -> 0x8f64d868
                                            } else {
                                                // 0x8f64d84c
                                                memcpy(v38, v39, v36 * v34);
                                                int32_t v42 = v6 + v8 * *(int32_t *)(g11 + 28); // 0x8f64d860
                                                v8 = v10;
                                                v40 = v42;
                                                // branch -> 0x8f64d868
                                            }
                                            // 0x8f64d868
                                            v32 = v22;
                                            v28 = v10;
                                            v33 = v40;
                                            // branch -> 0x8f64d870
                                        }
                                        // 0x8f64d870
                                        v21 = *(int32_t *)(g11 + 28) * v32 + v37;
                                        v26 = v33;
                                        // branch -> 0x8f64d884
                                      lab_0x8f64d884_7:
                                        // 0x8f64d884
                                        v27 = v21;
                                        v24 = v23;
                                        v25 = v26;
                                        v29 = v28;
                                        // branch -> 0x8f64d884
                                      lab_0x8f64d884_10:
                                        // 0x8f64d884
                                        if (v24 == 0) {
                                            // break -> 0x8f64d6d4
                                            break;
                                        }
                                        a6 = v29;
                                        v6 = v25;
                                        a2 = v24;
                                        v7 = v27;
                                        // continue -> 0x8f64d6dc
                                        continue;
                                    }
                                    // 0x8f64d870
                                    v21 = *(int32_t *)(g11 + 28) * v20 + v30;
                                    v28 = a6 - v20;
                                    v26 = v6;
                                    // branch -> 0x8f64d884
                                    goto lab_0x8f64d884_7;
                                }
                                // 0x8f64d870
                                v21 = *(int32_t *)(g11 + 28) * v32 + v31;
                                v26 = v33;
                                // branch -> 0x8f64d884
                                goto lab_0x8f64d884_7;
                            }
                        }
                        // 0x8f64d8d4
                        // branch -> 0x8f64d8d8
                    } else {
                        uint32_t v43 = v20 % 0x8000; // 0x8f64d6f0
                        if (a2 < v43) {
                            // after_if_8f64d700_0.thread
                            // branch -> 0x8f64d8cc
                        } else {
                            // after_if_8f64d700_0
                            if ((v43 > 1 ? 0 : 1 - v43) == 0) {
                                int32_t v44 = a2 - v43; // 0x8f64d710
                                v23 = v44;
                                int32_t v45 = v7 + 5; // 0x8f64d714
                                v21 = v45;
                                if (v10 != 0) {
                                    v27 = v45;
                                    v24 = v44;
                                    v25 = v6;
                                    v29 = a6;
                                    goto lab_0x8f64d884_10;
                                }
                                // 0x8f64d71c
                                if (a6 < v43) {
                                    // if_8f64d720_0_true
                                    v28 = a6 - v43;
                                    v26 = v6;
                                    // branch -> 0x8f64d884
                                    goto lab_0x8f64d884_7;
                                } else {
                                    char v46 = *(char *)(v7 + 2); // 0x8f64d728
                                    uint32_t v47 = v8; // 0x8f64d72c
                                    char v48 = *(char *)(v7 + 3); // 0x8f64d730
                                    char v49 = *(char *)(v7 + 4); // 0x8f64d734
                                    v9 = v49;
                                    if (v47 == 0) {
                                      lab_0x8f64d880:
                                        // 0x8f64d880
                                        v28 = 0;
                                        v26 = v6;
                                        // branch -> 0x8f64d884
                                        goto lab_0x8f64d884_7;
                                    } else {
                                        int32_t v50 = v43 - a6; // 0x8f64d744
                                        int32_t v51 = v50; // R1
                                        int32_t v52; // R2
                                        if (v47 > v50) {
                                            // 0x8f64d758
                                            v8 = v47 - v50;
                                            v22 = v50 - 1;
                                            if (v43 != a6) {
                                                while (true) {
                                                    // 0x8f64d76c
                                                    v52 = v6 + 3;
                                                    *(char *)(v6 + 2) = v49;
                                                    *(char *)(v52 - 3) = v46;
                                                    *(char *)(v52 - 2) = v48;
                                                    int32_t v53 = v22;
                                                    v22 = v53 - 1;
                                                    if (v53 != 0) {
                                                        // 0x8f64d76c
                                                        v49 = v9;
                                                        v6 = v52;
                                                        // branch -> 0x8f64d76c
                                                        continue;
                                                    } else {
                                                        // 0x8f64d764
                                                        // branch -> 0x8f64d788
                                                        // 0x8f64d788
                                                        v28 = 0;
                                                        v26 = 3 * v51 + v6;
                                                        // branch -> 0x8f64d884
                                                        goto lab_0x8f64d884_7;
                                                    }
                                                }
                                            }
                                            // 0x8f64d788
                                            v28 = 0;
                                            v26 = v6;
                                            // branch -> 0x8f64d884
                                            goto lab_0x8f64d884_7;
                                        } else {
                                            // 0x8f64d7a0
                                            v51 = v47 - 1;
                                            // branch -> 0x8f64d7a0
                                            while (true) {
                                                // 0x8f64d7a0
                                                v52 = v6 + 3;
                                                *(char *)(v6 + 2) = v49;
                                                *(char *)(v52 - 3) = v46;
                                                *(char *)(v52 - 2) = v48;
                                                int32_t v54 = v51;
                                                v51 = v54 - 1;
                                                if (v54 != 0) {
                                                    // 0x8f64d7a0
                                                    v49 = v9;
                                                    v6 = v52;
                                                    // branch -> 0x8f64d7a0
                                                    continue;
                                                } else {
                                                    int32_t v55 = v6 + 3 * v8; // 0x8f64d7c0
                                                    v8 = 0;
                                                    v6 = v55;
                                                    // branch -> 0x8f64d880
                                                    goto lab_0x8f64d880;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        // 0x8f64d8cc
                        // branch -> 0x8f64d8d8
                    }
                    // 0x8f64d8d8
                    if (v1 != g24) {
                        // 0x8f64d8ec
                        __stack_chk_fail();
                        // branch -> 0x8f64d8f0
                    }
                    // 0x8f64d8f0
                    return 0;
                }
            }
            // 0x8f64d8d8
            int32_t result; // 0x8f64d8f4_2
            if (v1 != g24) {
                // 0x8f64d8ec
                __stack_chk_fail();
                result = v9;
                // branch -> 0x8f64d8f0
            } else {
                int32_t v56; // bp+263
                result = v56;
            }
            // 0x8f64d8f0
            return result;
        }
    }
    // 0x8f64d8c4
    // branch -> 0x8f64d8d8
    // 0x8f64d8d8
    if (v1 != g24) {
        // 0x8f64d8ec
        __stack_chk_fail();
        // branch -> 0x8f64d8f0
    }
    // 0x8f64d8f0
    return 1;
}

// --------------- Statically Linked Functions ----------------

// ulldiv_t __aeabi_uldivmod(unsigned long long a, unsigned long long b);
// void __stack_chk_fail(void);
// void free(void * ptr);
// void * malloc(size_t size);
// void * memalign(size_t alignment, size_t size);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int snprintf(char * restrict s, size_t maxlen, const char * restrict format, ...);
// char * strchr(char * s, int c);
// int strcmp(const char * s1, const char * s2);
// char * strcpy(char * restrict dest, const char * restrict src);
// size_t strlen(const char * s);
// int strncmp(const char * s1, const char * s2, size_t n);
// char * strncpy(char * restrict dest, const char * restrict src, size_t n);
// size_t strnlen(const char * string, size_t maxlen);
// char * strrchr(char * s, int c);
// size_t strspn(const char * s, const char * accept);
// char * strstr(char * haystack, const char * needle);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 22
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 18:49:08
