//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t allocate_sp_block(int32_t * a1, int32_t a2, uint32_t a3, int32_t a4);
int32_t clear_sparse_data_list(int32_t a1, int32_t a2);
int32_t create_sp_block(int32_t a1, int32_t a2);
int32_t flush_sp_header(void);
int32_t free_sparse_data(char * a1, int32_t a2);
int32_t get_entry_index_by_name(char * str, int32_t a2, int32_t a3);
int32_t get_first_sparse_data(int32_t a1, int32_t a2, int32_t a3);
int32_t get_last_sparse_data(int32_t a1, int32_t a2, int32_t a3);
int32_t get_next_sparse_data(int32_t a1, int32_t a2, int32_t a3);
int32_t get_output_block_count(int32_t a1, int32_t a2, int32_t a3);
int32_t get_prev_sparse_data(int32_t a1, int32_t a2, int32_t a3);
int32_t init_free_blocks(void);
int32_t init_sp_partition(char * a1, int32_t a2);
int32_t is_sparse_image(int32_t * a1, int32_t a2, int32_t a3);
int32_t move_to_sparse_data(int32_t a1, int32_t result, int32_t a3);
int32_t remove_sparse_data(int32_t a1, int32_t a2);
int32_t speedo_find(void);
int32_t speedo_start(int32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g18 = 0; // R0
int32_t g19 = 0; // R1
int32_t g20 = 0; // R2
int32_t g21 = 0; // R3
int32_t g22 = 0; // R4
int32_t g23 = 0; // R5
int32_t g24 = 0; // R6
int32_t g25 = 0; // R7
int32_t g26 = 0; // R8
int32_t g1 = 1; // 0x8f6ac0f0
int32_t g2 = 0; // 0x8f710c38
int32_t g3 = 0; // 0x8f710c3c
int32_t g4 = 0; // 0x8f710c40
int32_t g5 = 0; // 0x8f710c44
char * g6; // 0x8f710c48
int32_t g7 = 0; // 0x8f710c50
int32_t g8 = 0; // 0x8f710c60
int32_t g9 = 0; // 0x8f710c64
int32_t g10 = 0; // 0x8f710c68
char * g11; // 0x8f710c70
int32_t g12 = 0; // 0x8f710e48
int32_t g13 = 0; // 0x8f710e78
int32_t g14 = 0; // 0x8f710e7c
int32_t g15 = 0; // 0x8f710e80
int32_t g16 = 0; // 0x8f710e84
int32_t g17 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f676b00 - 0x8f676ba3
int32_t flush_sp_header(void) {
    int32_t v1 = (int32_t)&g6; // R4
    int32_t v2 = g17;
    int32_t v3 = crc32(255, (char *)&g11, 512); // 0x8f676b24
    g9 = 0;
    g10 = v3;
    g9 = crc32(255, (char *)v1, 552);
    int32_t v4;
    int32_t v5 = generic_mmc_write_logical(g4, g5, 552, 0, v1, 0, 0, v2, 0, g22, g23, 0, v4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0); // 0x8f676b5c
    int32_t result = v5; // R0
    int32_t v6 = 0; // 0x8f676b90_22
    if (v5 != 0) {
        // 0x8f676b68
        print_log(-1, (int32_t)"Failed to flush SP header\n", 552, 0, v1, 0, 0, v2, 0, g22, g23, 0, v4);
        result = -1;
        v6 = -1;
        // branch -> 0x8f676b78
    }
    // 0x8f676b78
    g20 = v2;
    if (v2 != g17) {
        // 0x8f676b88
        __stack_chk_fail();
        // branch -> 0x8f676b8c
    } else {
        result = v6;
    }
    // 0x8f676b8c
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void * calloc(size_t nmemb, size_t size);
// uLong crc32(uLong crc, const Bytef * buf, uInt len);
// void free(void * ptr);
// void * malloc(size_t size);
// void * memset(void * s, int c, size_t n);
// int strncmp(const char * s1, const char * s2, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 18
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 18:53:38
