//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <ctype.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t append_log(char * a1, int32_t a2);
int32_t flush_all_ram_log(void);
int32_t flush_ram_logs(uint32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t freeset(int32_t a1, int32_t * a2, int32_t a3, int32_t a4);
int32_t get_boot_seq(int32_t a1, int32_t a2, int32_t a3);
int32_t get_checksum_constprop_3(int32_t a1, int32_t a2, int32_t a3);
int32_t get_first_ram_log(int32_t a1, int32_t a2, int32_t a3);
int32_t get_log_line_from_buffer(void);
int32_t get_next_ram_log(int32_t a1, int32_t a2);
int32_t md5_init(int32_t * a1, int32_t result, int32_t a3);
char * md5_process(int32_t a1, char * a2);
int32_t p_b_coll_elem(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t p_b_symbol(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t p_count(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t ram_logger_early_init(int32_t a1, int32_t a2, int32_t a3);
int32_t ram_logger_init(int32_t a1, int32_t a2);
int32_t ram_logger_output(char * a1);
int32_t seterr(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);

// --------------------- Global Variables ---------------------

int32_t g20 = 0; // LR
int32_t g21 = 0; // R0
int32_t g22 = 0; // R1
int32_t g23 = 0; // R10
int32_t g24 = 0; // R11
int32_t g25 = 0; // R2
int32_t g26 = 0; // R4
int32_t g27 = 0; // R5
int32_t g28 = 0; // R6
int32_t g29 = 0; // R7
int32_t g30 = 0; // R8
int32_t g31 = 0; // R9
char * g1; // 0x8f6576f8
char * g2; // 0x8f657e58
char * g3 = "\x01"; // 0x8f6a4258
char (*g4)[4] = "SOH"; // 0x8f6a4524
char * g5 = "\x01"; // 0x8f6aff30
char g6 = 0; // 0x8f6aff5c
char * g7 = "\x01"; // 0x8f6aff80
char * g8; // 0x8f6ed810
int32_t g9 = 0; // 0x8f6ed814
int32_t g10 = 0; // 0x8f6ed818
int64_t g11 = 0; // 0x8f6ed820
int32_t g12 = 0; // 0x8f6ed824
int32_t g13 = 0; // 0x8f6ed828
int32_t g14 = 0; // 0x8f6ed82c
int32_t g15 = 0; // 0x8f6ed830
char * g16; // 0x8f6ed834
int32_t g17 = 0; // 0x8f6ed838
int32_t g18 = 0; // 0x8f70da8d
char * g19; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f65b260 - 0x8f65b357
int32_t freeset(int32_t a1, int32_t * a2, int32_t a3, int32_t a4) {
    int32_t v1 = (int32_t)a2;
    char * v2 = g19;
    if (a1 == 0) {
        // 0x8f65b284
        _panic(g20, (int32_t)"ASSERT FAILED at (%s:%d): %s\n", (int32_t)"lib/regex/regcomp.c", (int32_t)"p != ((void *)0)" & -0x10000 | 1293, (int32_t)"p != ((void *)0)", v1, a3);
        // branch -> 0x8f65b2a0
    }
    // 0x8f65b2a0
    if (v1 == 0) {
        // 0x8f65b2a8
        _panic(g20, (int32_t)"ASSERT FAILED at (%s:%d): %s\n", (int32_t)"lib/regex/regcomp.c", (int32_t)"cs != ((void *)0)" & -0x10000 | 1294, (int32_t)"cs != ((void *)0)", v1, a3);
        // branch -> 0x8f65b2c4
    }
    int32_t v3 = *(int32_t *)(a1 + 28); // 0x8f65b2c4
    int32_t v4 = *(int32_t *)(v3 + 8); // 0x8f65b2d0
    int32_t result = *(int32_t *)(v3 + 16) + 16 * *(int32_t *)(v3 + 12); // 0x8f65b2d8
    int32_t * v5; // 0x8f65b31c_1
    if (v4 == 0) {
        // 0x8f65b310
        if (v1 == result - 16) {
            // if_8f65b318_0_true
            v5 = (int32_t *)(*(int32_t *)(a1 + 28) + 12);
            *v5 = *v5 - 1;
            // branch -> after_if_8f65b324_0
        }
        // after_if_8f65b324_0
        if (v2 != g19) {
            // 0x8f65b338
            __stack_chk_fail();
            // branch -> 0x8f65b33c
        }
        // 0x8f65b33c
        return result;
    }
    char v6 = *(char *)(v1 + 4); // 0x8f65b2ec
    char * v7 = (char *)*(int32_t *)v1; // 0x8f65b2f0_0
    char v8 = *v7; // 0x8f65b2f0
    *v7 = (char)((int32_t)v8 & -1 - (int32_t)v6);
    char * v9 = (char *)(v1 + 5); // 0x8f65b2fc_0
    int32_t v10 = 0; // 0x8f65b300
    int32_t v11 = v10 + 1; // R3
    *v9 = (char)((int32_t)*v9 - v10);
    while (v11 != v4) {
        // 0x8f65b2e4
        v6 = *(char *)(v1 + 4);
        v7 = (char *)(*(int32_t *)v1 + v11 % 256);
        v8 = *v7;
        *v7 = (char)((int32_t)v8 & -1 - (int32_t)v6);
        v9 = (char *)(v1 + 5);
        v10 = v11;
        v11 = v10 + 1;
        *v9 = (char)((int32_t)*v9 - v10);
        // continue -> 0x8f65b2e4
    }
    // 0x8f65b310
    if (v1 == result - 16) {
        // if_8f65b318_0_true
        v5 = (int32_t *)(*(int32_t *)(a1 + 28) + 12);
        *v5 = *v5 - 1;
        // branch -> after_if_8f65b324_0
    }
    // after_if_8f65b324_0
    if (v2 != g19) {
        // 0x8f65b338
        __stack_chk_fail();
        // branch -> 0x8f65b33c
    }
    // 0x8f65b33c
    return result;
}

// --------------- Statically Linked Functions ----------------

// ulldiv_t __aeabi_uldivmod(unsigned long long a, unsigned long long b);
// void __stack_chk_fail(void);
// int isdigit(int c);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int snprintf(char * restrict s, size_t maxlen, const char * restrict format, ...);
// size_t strlen(const char * s);
// int strncmp(const char * s1, const char * s2, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 18
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 18:51:02
