//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t board_baseband(int32_t a1);
int32_t board_target_id(int32_t a1);
int32_t clk_get_parent(void);
int32_t cmd_flash_mmc_img(char * a1, char * a2, int32_t a3);
int32_t disable_cont_splash_screen(int32_t a1, int32_t a2);
int32_t enable_cont_splash_screen(int32_t a1);
int32_t flash_partition(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t gfx_surface_destroy(char * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t hab_rsa_init(void);
int32_t heap_insert_free_chunk(int32_t * a1, int32_t a2);
int32_t is_backup_needed(int32_t a1, int32_t a2, int32_t a3);
int32_t is_most_like_hab_image(int32_t a1, int32_t a2, int32_t a3);
int32_t is_skip_sparse_preflash_validation(int32_t result, int32_t a2);
int32_t mask_interrupt(int32_t a1);
int32_t mcs_DER_decodeContents(int32_t a1);
int32_t mcs_DER_recordLength(int32_t a1);
int32_t mdss_dsi_phy_regulator_init(int32_t * a1, int32_t a2);
int32_t mdss_dsi_v2_phy_init(int32_t a1, int32_t a2);
int32_t mot_sst_get_security_state(void);
int32_t mot_sst_oem_lock_handler(int32_t a1, int32_t a2);
int32_t register_int_handler(int32_t a1, int32_t a2, int32_t a3);
int32_t set_logo(char a1, int32_t a2, int32_t a3);
int32_t set_logo_screen_mode(char a1, int32_t a2, int32_t a3);
int32_t smem_get_ram_ptable_len(int32_t a1, int32_t a2, int32_t a3);
int32_t smem_get_ram_ptable_version(void);
int32_t timer_cancel(int32_t result, int32_t a2);
int32_t timer_init(int32_t a1, int32_t a2);
int32_t udc_interrupt(int32_t a1, int32_t a2);
int32_t ulpi_read(uint32_t a1, int32_t a2);
int32_t unmask_interrupt(int32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g51 = 0; // LR
int32_t g52 = 0; // R0
int32_t g53 = 0; // R1
int32_t g54 = 0; // R10
int32_t g55 = 0; // R11
int32_t g56 = 0; // R12
int32_t g57 = 0; // R2
int32_t g58 = 0; // R3
int32_t g59 = 0; // R4
int32_t g60 = 0; // R5
int32_t g61 = 0; // R6
int32_t g62 = 0; // R7
int32_t g63 = 0; // R8
int32_t g64 = 0; // R9
int32_t g1 = -0x1a60cf24; // 0x8f61c060
char * g2[12] = {
    "GET_STATUS",
    "CLEAR_FEATURE",
    "*UNKNOWN*",
    "SET_FEATURE",
    "*UNKNOWN*",
    "SET_ADDRESS",
    "GET_DESCRIPTOR",
    "SET_DESCRIPTOR",
    "GET_CONFIGURATION",
    "SET_CONFIGURATION",
    "GET_INTERFACE",
    "SET_INTERFACE"
}; // 0x8f67d234
int32_t g3 = 0; // 0x8f69eef0
char * g4 = "\x01"; // 0x8f6a84ee
int32_t g6 = 0; // 0x8f6ac07c
int32_t g7 = 0; // 0x8f6ac080
int32_t g8 = 1; // 0x8f6ac0f0
char * g9 = "\x01"; // 0x8f6ac220
char g10 = 0; // 0x8f6b50b0
char g11 = 0; // 0x8f6b50b1
char g12 = 0; // 0x8f6b50b2
char g13 = 0; // 0x8f6b50b3
char g14 = 0; // 0x8f6b50b8
char g15 = 0; // 0x8f6b50b9
char g16 = 0; // 0x8f6b50ba
char g17 = 0; // 0x8f6b50bb
int32_t g18 = 0; // 0x8f6b7920
int32_t g19 = 0; // 0x8f6b7924
char * g20; // 0x8f6b7928
int32_t g21 = 0; // 0x8f6b792c
int32_t g22 = 0; // 0x8f6b7934
int32_t g23 = 0; // 0x8f6b793c
int32_t g24 = 0; // 0x8f6b7944
int32_t g25 = 0; // 0x8f6b7948
int32_t g26 = 0; // 0x8f6c01d0
int32_t g27 = 0; // 0x8f6c01d4
char * g28; // 0x8f6e08f9
char * g29; // 0x8f6e0938
int32_t g30 = 0; // 0x8f6e0bf0
int32_t g31 = 0; // 0x8f6e0bf4
char * g32; // 0x8f70e724
char * g33; // 0x8f70fa25
int32_t g34 = 0; // 0x8f710c28
int32_t g35 = 0; // 0x8f710c2c
int32_t g36 = 0; // 0x8f710c30
int32_t g37 = 0; // 0x8f710c34
int32_t g38 = 0; // 0x8f7112f4
char * g39; // 0x8f71302c
int32_t g40 = 0; // 0x8f713030
int32_t g41 = 0; // 0x8f713034
int32_t g42 = 0; // 0x8f713036
int32_t g43 = 0; // 0x8f713038
int32_t g44 = 0; // 0x8f71303c
int32_t g45 = 0; // 0x8f713040
char * g46; // 0x8f713044
int32_t g47 = 0; // 0x8f713048
int32_t g48 = 0; // 0x8f71304c
int32_t g49 = 0; // 0x8f71304e
int32_t g50 = 0; // 0x8f713050
int32_t * g5 = &g3; // 0x8f6a9eec

// ------------------------ Functions -------------------------

// Address range: 0x8f675ecc - 0x8f6760e7
int32_t hab_rsa_init(void) {
    int32_t v1 = &g38; // R3
    int32_t str = g52; // 0x8f675ed4
    int32_t v2 = g38;
    int32_t v3 = v2; // R2
    int32_t str3 = g53; // 0x8f675ee0
    int32_t v4; // 0x8f67607c
    int32_t result; // 0x8f6760a0_2
    int32_t v5;
    int32_t v6;
    int32_t v7;
    if (str == 0) {
        // after_if_8f675ee4_0.thread
        v4 = &g38;
        // branch -> 0x8f67607c
        // 0x8f67607c
        print_log(0, (int32_t)"No SRK for boot component defined\n", v2, v4, v6, v5, 0, v2, 0, g59, g60, g61, g62);
        g52 = -1;
        // branch -> 0x8f676084
        // 0x8f676084
        g53 = &g38;
        g57 = v2;
        v7 = g38;
        g58 = v7;
        if (v2 != v7) {
            // 0x8f676098
            __stack_chk_fail();
            result = g52;
            // branch -> 0x8f67609c
        } else {
            result = -1;
        }
        // 0x8f67609c
        return result;
    }
    // 0x8f675ef0
    int32_t v8; // bp+228
    if (str3 == 0) {
        // if_8f675ef4_0_true
        v4 = &g38;
        // branch -> 0x8f67607c
        // 0x8f67607c
        print_log(0, (int32_t)"No SRK for AP images defined\n", v2, v4, v6, v5, 0, v2, 0, g59, g60, g61, g62);
        g52 = -1;
        v8 = -1;
        // branch -> 0x8f676084
    } else {
        int32_t v9 = &g44; // R5
        int32_t str4 = (int32_t)"SRK.CA614.wtls.crt"; // R4
        g45 = &g44;
        g44 = &g44;
        int32_t v10; // 0x8f67607c314
        int32_t v11; // R10
        int32_t v12; // R6
        int32_t v13; // R9
        int32_t v14;
        int32_t v15; // 0x8f676064
        int32_t v16; // 0x8f676068
        int32_t v17; // 0x8f67606c
        int32_t str2; // 0x8f675f70
        if ((int32_t)"SRK.CA614.wtls.crt" != (int32_t)&g5) {
            while (true) {
                char * mem = malloc(12); // 0x8f675f20
                int32_t v18 = (int32_t)mem; // 0x8f675f20_3
                if (mem == NULL) {
                    // 0x8f675f2c
                    print_log(-1, (int32_t)"Out of memory for SRK\n", v3, v1, v6, v5, 0, v2, 0, g59, g60, g61, g62);
                    // branch -> 0x8f675f58
                } else {
                    // 0x8f675f3c
                    v1 = g44;
                    *(int32_t *)(v18 + 8) = str4;
                    str4 += 352;
                    *(int32_t *)v9 = v18;
                    *(int32_t *)mem = v1;
                    *(int32_t *)(v18 + 4) = v9;
                    *(int32_t *)(v1 + 4) = v18;
                    if (str4 == (int32_t)&g5) {
                        // break -> 0x8f675f58
                        break;
                    }
                    // continue -> 0x8f675f1c
                    continue;
                }
                // 0x8f675f58
                v14 = g45;
                v12 = v14;
                v13 = 0;
                v11 = 0;
                v16 = 0;
                v15 = 0;
                int32_t v19 = v5;
                if (v14 != v9) {
                    int32_t v20 = v14; // 0x8f675f70
                    v10 = v5;
                    int32_t v21; // 0x8f67607c2
                    while (true) {
                        // 0x8f675f70
                        str2 = *(int32_t *)(v20 + 8);
                        str4 = str2;
                        if (strncmp((char *)str, (char *)str2, 64) == 0) {
                          lab_0x8f675f8c:
                            // 0x8f675f8c
                            v11 = str4 + 64;
                            print_log(1, (int32_t)"got boot srk %s\n", str, v1, v6, v10, 0, v2, 0, g59, g60, g61, g62);
                            g35 = v11;
                            memcpy((char *)&g39, (char *)&g4, 4);
                            g40 = v11;
                            *(int16_t *)&g41 = 3;
                            v11 = 1;
                            *(char *)&g43 = 1;
                            *(int16_t *)&g42 = 256;
                            int32_t v22 = str4 + 320; // 0x8f675fd8
                            v1 = v22;
                            g37 = v22;
                            // branch -> 0x8f675fe0
                        } else {
                          lab_0x8f675f70:;
                            // 0x8f675f70
                            // branch -> 0x8f675fe0
                        }
                        // 0x8f675fe0
                        v3 = 64;
                        v21 = v10;
                        if (strncmp((char *)str3, (char *)str4, 64) == 0) {
                            // 0x8f675ff8
                            print_log(1, (int32_t)"got AP srk %s\n", str3, v1, v6, v10, 0, v2, 0, g59, g60, g61, g62);
                            int32_t v23 = str4; // 0x8f676010
                            int32_t v24 = v23 + 64; // 0x8f676010
                            int32_t v25 = (int32_t)&g46; // 0x8f676018
                            g34 = v24;
                            memcpy((char *)v25, (char *)&g4, 4);
                            v3 = &g36;
                            g47 = v24;
                            *(int16_t *)&g48 = 3;
                            *(int16_t *)&g49 = 256;
                            v1 = 1;
                            *(char *)&g50 = 1;
                            v13 = 1;
                            g36 = v23 + 320;
                            v21 = v24;
                            // branch -> 0x8f67605c
                        }
                        int32_t v26 = *(int32_t *)(v12 + 4); // 0x8f67605c
                        v12 = v26;
                        if (v26 == v9) {
                            // break -> 0x8f675f68
                            break;
                        }
                        v20 = v26;
                        v10 = v21;
                        // continue -> 0x8f675f70
                    }
                    // 0x8f675f68
                    v16 = v11;
                    v15 = v13;
                    v19 = v21;
                    // branch -> 0x8f676064
                }
                // 0x8f676064
                v17 = v15 ^ 1 | v16 ^ 1;
                g52 = v17;
                v8 = v17;
                if (v15 != v16) {
                    // 0x8f676074
                    // branch -> 0x8f67607c
                    // 0x8f67607c
                    print_log(0, (int32_t)"Incompleted SRK settings\n", v3, v1, v6, v19, 0, v2, 0, g59, g60, g61, g62);
                    g52 = -1;
                    v8 = -1;
                    // branch -> 0x8f676084
                }
                // 0x8f676084
                g53 = &g38;
                g57 = v2;
                v7 = g38;
                g58 = v7;
                if (v2 != v7) {
                    // 0x8f676098
                    __stack_chk_fail();
                    result = g52;
                    // branch -> 0x8f67609c
                } else {
                    result = v8;
                }
                // 0x8f67609c
                return result;
            }
        }
        // 0x8f675f58
        v14 = g45;
        v12 = v14;
        v13 = 0;
        v11 = 0;
        v16 = 0;
        v15 = 0;
        if (v14 != v9) {
            v10 = v5;
            while (true) {
                // 0x8f675f70
                str2 = *(int32_t *)(v14 + 8);
                str4 = str2;
                if (strncmp((char *)str, (char *)str2, 64) == 0) {
                    goto lab_0x8f675f8c;
                }
                goto lab_0x8f675f70;
            }
        }
        // 0x8f676064
        v17 = v15 ^ 1 | v16 ^ 1;
        g52 = v17;
        if (v15 != v16) {
            // 0x8f676074
            // branch -> 0x8f67607c
            // 0x8f67607c
            print_log(0, (int32_t)"Incompleted SRK settings\n", v3, v1, v6, v5, 0, v2, 0, g59, g60, g61, g62);
            g52 = -1;
            v8 = -1;
            // branch -> 0x8f676084
        } else {
            v8 = v17;
        }
    }
    // 0x8f676084
    g53 = &g38;
    g57 = v2;
    v7 = g38;
    g58 = v7;
    if (v2 != v7) {
        // 0x8f676098
        __stack_chk_fail();
        result = g52;
        // branch -> 0x8f67609c
    } else {
        result = v8;
    }
    // 0x8f67609c
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void free(void * ptr);
// void * malloc(size_t size);
// int memcmp(const void * s1, const void * s2, size_t n);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int strcmp(const char * s1, const char * s2);
// size_t strlen(const char * s);
// int strncmp(const char * s1, const char * s2, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 30
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 19:42:21
