//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t arch_context_switch(int32_t a1, int32_t a2, int32_t a3);
int32_t arch_early_init(void);
int32_t arch_init(int32_t a1, int32_t a2);
int32_t arch_thread_initialize(int32_t a1, int32_t a2, int32_t a3);
int32_t bptools_mode(int32_t a1, int32_t a2, int32_t a3);
int32_t confession_get_buffer(int32_t a1, int32_t a2, int32_t a3);
int32_t confession_printf(char * a1, int32_t a2);
int32_t fboot_usb_init(int32_t a1, int32_t a2, int32_t a3);
int32_t fboot_usb_write(int32_t a1, int32_t a2);
int32_t fboot_usb_write_queue(int32_t a1, uint32_t a2, int32_t a3);
int32_t fboot_usb_write_wait(int32_t a1, int32_t a2, int32_t a3);
int32_t generic_mmc_init(char * a1, int32_t a2);
int32_t generic_mmc_read_sector(int64_t a1, int64_t a2, int32_t a3, int32_t a4);
int32_t hab_su_code(int32_t a1, int32_t a2);
int32_t hab_su_srk_selection(int32_t a1, int32_t a2);
int32_t handle_fboot_command_erase(int32_t a1, int32_t a2);
int32_t handle_fboot_command_multiflash(int32_t * a1);
int32_t is_qcom_mode(void);
int32_t mcs_DER_decode(char * a1, int16_t * a2, char * a3, int16_t * a4);
int32_t mcs_DER_decodeItem(int32_t a1, int32_t a2, int32_t a3);
char * mmc_get_card_status_isra_3(char * a1, int32_t * a2, int32_t * a3);
int32_t pm8x41_reset_configure(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t power_source_detected(int32_t a1, int32_t a2, int32_t a3);
int32_t remove_sp_block(int32_t a1);
int32_t sdhci_mode_disable(int32_t a1);
int32_t SecBoundSigAllowed(void);
int32_t SecICTypeRead(void);
int32_t smb1359_init(int32_t a1, int32_t a2, int32_t a3);
int32_t smb1359_masked_write_reg(int32_t a1, int32_t a2, int32_t a3);
int32_t update_sp_block(int32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

bool g28 = false; // LR
int32_t g29 = 0; // R0
int32_t g30 = 0; // R1
int32_t g31 = 0; // R10
int32_t g32 = 0; // R2
int32_t g33 = 0; // R3
int32_t g34 = 0; // R4
int32_t g35 = 0; // R5
int32_t g36 = 0; // R6
int32_t g37 = 0; // R7
int32_t g38 = 0; // R8
int32_t g39 = 0; // R9
int32_t g1 = -0x15fffffa; // 0x8f600000
int32_t g2 = -0x1a60cfa4; // 0x8f619a9c
int32_t g3 = -0x1a60cfc4; // 0x8f62d6e8
char * g4 = "\n"; // 0x8f6ac1b0
int32_t g5 = -0x709d28c8; // 0x8f6ac1cc
int32_t g6 = 0; // 0x8f6c03b4
int32_t g7 = 0; // 0x8f6c064c
int32_t g8 = 0; // 0x8f6c0650
int32_t g9 = 0; // 0x8f6c0654
int32_t g10 = 0; // 0x8f6c0658
int32_t g11 = 0; // 0x8f6c065c
int32_t g12 = 0; // 0x8f6c0660
int32_t g13 = 0; // 0x8f6c0664
int32_t g14 = 0; // 0x8f6c0668
int32_t g15 = 0; // 0x8f6c066c
int32_t g16 = 0; // 0x8f6e0bd4
char * g17; // 0x8f6e12e8
int32_t g18 = 0; // 0x8f6e12ec
int32_t g19 = 0; // 0x8f6e12f0
int32_t g20 = 0; // 0x8f710c38
char * g21; // 0x8f710c3c
int32_t g22 = 0; // 0x8f710c48
int32_t g23 = 0; // 0x8f710c60
char * g24; // 0x8f710e74
int32_t g25 = 0; // 0x8f7112f4
int32_t g26 = 0; // 0x8f711534
char * g27; // 0x8f7125ec

// ------------------------ Functions -------------------------

// Address range: 0x8f623db0 - 0x8f623e83
int32_t handle_fboot_command_erase(int32_t a1, int32_t a2) {
    int32_t v1 = g28 ? -0x709af928 : 0; // 0x8f623db0
    int32_t v2 = g25;
    set_flash_fail(a1);
    int32_t str = *(int32_t *)(a1 + 12) + 1; // 0x8f623dcc
    int32_t v3;
    int32_t result;
    if (erase_partition(str, a2, g32, v2, a1, v2, g34) == -1) {
        // 0x8f623de0
        print_log(0, (int32_t)"Failed to erase partition %s\n", str, v2, a1, v2, g34, g35, g36, v1, v3, 0, 0);
        result = 3;
        // branch -> 0x8f623e50
    } else {
        int32_t strcmp_rc = strcmp((char *)str, "utags"); // 0x8f623e00
        if (strcmp_rc == 0) {
            // 0x8f623e0c
            erase_partition((int32_t)"utagsBackup", (int32_t)"utags", g32, v2, a1, v2, g34);
            __utags_invalidate(strcmp_rc, (int32_t)"utags", g32, v2, a1, v2, g34, g35, g36, v1);
            // branch -> 0x8f623e1c
        }
        int32_t strcmp_rc2 = strcmp((char *)str, "hw"); // 0x8f623e24
        int32_t v4 = strcmp_rc2; // 0x8f623e38
        if (strcmp_rc2 == 0) {
            // 0x8f623e30
            v4 = __utags_invalidate(1, (int32_t)"hw", g32, v2, a1, v2, g34, g35, g36, v1);
            // branch -> 0x8f623e38
        }
        // 0x8f623e38
        clear_flash_fail(v4, (int32_t)"hw", g32);
        print_log(1, (int32_t)"Succeeded to erase partition %s\n", str, v2, a1, v2, g34, g35, g36, v1, v3, 0, 0);
        result = 1;
        // branch -> 0x8f623e50
    }
    // 0x8f623e50
    if (v2 != g25) {
        // 0x8f623e60
        __stack_chk_fail();
        // branch -> 0x8f623e64
    }
    // 0x8f623e64
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void free(void * ptr);
// void * malloc(size_t size);
// void * memset(void * s, int c, size_t n);
// int sprintf(char * restrict s, const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);
// int vsnprintf(char * restrict s, size_t maxlen, const char * restrict format, _G_va_list arg);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 30
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 19:29:09
