//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <ctype.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t clk_get(char * str2);
int32_t clk_get_set_enable(int32_t a1, int32_t a2, int32_t a3);
int32_t dbval_provision_req(char a1, char * a2, int32_t a3);
int32_t dbval_provision_store(char * a1, int32_t * a2, char * a3);
int32_t event_signal(int32_t a1, int32_t a2, int32_t a3);
void event_unsignal(int32_t a1);
int32_t fboot_info(char * str, char * format, int32_t a3, int32_t a4);
void function_8f67b3c0(void);
int32_t generic_mmc_erase_sector(int64_t a1, int64_t a2);
int32_t generic_mmc_get_protect_group_size(int32_t a1, int32_t a2);
int32_t get_root_detect_disabled(void);
int32_t hab_map_address(int32_t a1, int32_t a2, int32_t a3);
int32_t hab_virtual_to_physical(int32_t a1, int32_t a2, int32_t a3);
int32_t handle_fboot_command_download(int32_t * a1);
int32_t mcs_clear_hash_ctx(char * a1, int32_t a2, int32_t a3);
int32_t mcs_initialize_montgomery_alg(int32_t * a1, int32_t a2);
int32_t mcs_memmove(uint32_t a1, uint32_t a2, int32_t a3);
int32_t mcs_memset(char * a1, char a2, int32_t a3);
int32_t mdss_dsi_auto_pll_config(int32_t * a1, int32_t a2);
int32_t mdss_dsi_host_init(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t mdss_dsi_phy_init(int32_t a1, int32_t a2, int32_t a3);
int32_t mipi_dsi_cmd_bta_sw_trigger(int32_t a1, int32_t a2, int32_t a3);
int32_t nexus_usbpidvid(int32_t a1, int32_t a2);
char * sdhci_msm_execute_tuning(char * a1, int32_t a2, int32_t a3);
int32_t sdhci_msm_toggle_cdr(int32_t * a1, int32_t a2, int32_t a3);
int32_t sod_init(void);
int32_t sod_ramdump_run(void);
int32_t thread_init(int32_t a1, int32_t a2);
int32_t thread_set_name(int32_t a1);

// --------------------- Global Variables ---------------------

int32_t g23 = 0; // LR
int32_t g24 = 0; // R0
int32_t g25 = 0; // R1
int32_t g26 = 0; // R10
int32_t g27 = 0; // R11
int32_t g28 = 0; // R2
int32_t g29 = 0; // R3
int32_t g30 = 0; // R4
int32_t g31 = 0; // R5
int32_t g32 = 0; // R6
int32_t g33 = 0; // R7
int32_t g34 = 0; // R8
int32_t g35 = 0; // R9
int32_t g1 = -0x15ffffb3; // 0x8f6361f4
char * g2 = "\xff\xff"; // 0x8f67d950
int32_t g3 = 0xff0fff; // 0x8f67db7c
int32_t g4 = 0x6d0f0703; // 0x8f67f558
int32_t g5 = 0x1c9496e0; // 0x8f67f5a0
int32_t g6 = 0x65440030; // 0x8f69c66f
int32_t g7 = 1; // 0x8f6ac0f0
int32_t g8 = -1; // 0x8f6ac214
int32_t g9 = -0x70a00000; // 0x8f6ac224
char * g10 = "\xf1"; // 0x8f6affa8
int32_t g11 = 0; // 0x8f6b7988
int32_t g12 = 0; // 0x8f6b798c
int32_t g13 = 0; // 0x8f6b8ad0
int32_t g14 = 0; // 0x8f6b8ad4
int32_t (*g15)(int32_t, int32_t, int32_t) = NULL; // 0x8f6e0784
int32_t g16 = 0; // 0x8f6e0790
char * g17; // 0x8f6e0794
int16_t * g18 = NULL; // 0x8f70da9c
int32_t g19 = 0; // 0x8f70da9e
int32_t g20 = 0; // 0x8f7112f4
int32_t g21 = 0; // 0x8f7114ac
int32_t g22 = 0; // 0x8f7125ec

// ------------------------ Functions -------------------------

// Address range: 0x8f667348 - 0x8f6673b3
int32_t mcs_memmove(uint32_t a1, uint32_t a2, int32_t a3) {
    // 0x8f667348
    g25 = a2;
    g28 = a3;
    int32_t result = g20;
    int32_t v1; // R3
    int32_t v2;
    if (a2 <= a1) {
        // 0x8f667368
        if (a3 == 0) {
            // 0x8f66737c
            g28 = result;
            v2 = g20;
            v1 = v2;
            if (result != v2) {
                goto lab_0x8f66738c_4;
            }
            // 0x8f6673a8
            return result;
        }
        int32_t v3 = a3 - 1; // 0x8f66736c
        *(char *)(v3 + a1) = *(char *)(v3 + a2);
        while (v3 != 0) {
            // if_8f66736c_0_true
            v3--;
            *(char *)(v3 + a1) = *(char *)(v3 + a2);
            // continue -> if_8f66736c_0_true
        }
        // 0x8f66737c
        g28 = result;
        v2 = g20;
        v1 = v2;
        if (result != v2) {
            goto lab_0x8f66738c_4;
        }
        // 0x8f6673a8
        return result;
    }
    // if_8f667360_0_true
    v1 = 0;
    int32_t v4 = 0; // 0x8f6673909
    // branch -> 0x8f667390
    // 0x8f667390
    if (v4 != a3) {
        int32_t v5 = v4; // 0x8f667398
        while (true) {
          lab_0x8f667398:
            // 0x8f667398
            *(char *)(v5 + a1) = *(char *)(v5 + a2);
            int32_t v6 = v1 + 1; // 0x8f6673a0
            v1 = v6;
            if (v6 == g28) {
                // break -> 0x8f66737c
                break;
            }
            v5 = v6;
            // continue -> 0x8f667398
        }
      lab_0x8f66737c:
        // 0x8f66737c
        g28 = result;
        v2 = g20;
        v1 = v2;
        if (result == v2) {
            // 0x8f6673a8
            return result;
        }
      lab_0x8f66738c_4:
        // 0x8f66738c
        __stack_chk_fail();
        v4 = v1;
        // branch -> 0x8f667390
        // 0x8f667390
        if (v4 == g28) {
            goto lab_0x8f66737c;
        }
        v5 = v4;
        goto lab_0x8f667398;
    }
    // 0x8f66737c
    g28 = result;
    v2 = g20;
    v1 = v2;
    if (result != v2) {
        goto lab_0x8f66738c_4;
    }
    // 0x8f6673a8
    return result;
}

// --------------- Statically Linked Functions ----------------

// ulldiv_t __aeabi_uldivmod(unsigned long long a, unsigned long long b);
// void __stack_chk_fail(void);
// void free(void * ptr);
// int isspace(int c);
// void * malloc(size_t size);
// void * memalign(size_t alignment, size_t size);
// int memcmp(const void * s1, const void * s2, size_t n);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int sprintf(char * restrict s, const char * restrict format, ...);
// int strcmp(const char * s1, const char * s2);
// size_t strlen(const char * s);
// char * strncpy(char * restrict dest, const char * restrict src, size_t n);
// size_t strnlen(const char * string, size_t maxlen);
// int vsnprintf(char * restrict s, size_t maxlen, const char * restrict format, _G_va_list arg);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 29
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 19:53:15
