//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t mdss_smp_alloc(int32_t a1, int32_t a2, int32_t a3, int32_t result2);
int32_t mdss_source_pipe_config(int32_t * a1, int32_t * a2, int32_t * a3);

// ------------------------ Functions -------------------------

// Address range: 0x8f60df70 - 0x8f60e057
int32_t mdss_source_pipe_config(int32_t * a1, int32_t * a2, int32_t * a3) {
    int32_t v1 = (int32_t)a1;
    int32_t v2 = (int32_t)a2;
    int32_t v3 = (int32_t)a3;
    uint32_t v4 = *(int32_t *)(v1 + 4); // 0x8f60df7c
    int32_t v5 = 0x10000 * *(int32_t *)(v1 + 8); // 0x8f60df84
    int32_t v6 = v5 + v4; // 0x8f60df88
    char v7 = *(char *)(v2 + 112); // 0x8f60df90
    int32_t v8 = v7; // R3
    int32_t v9; // R12
    int32_t v10; // 0x8f60dfd0
    int32_t result; // 0x8f60dfd4
    if (v7 == 0) {
        // if_8f60df98_0_true
        v9 = v6;
        // branch -> 0x8f60dfcc
    } else {
        // 0x8f60dfa0
        v9 = v4 / 2 + v5;
        if (a3 != (int32_t *)0x1a27000) {
            // 0x8f60dfb0
            if ((v3 & -0x10001) != 0x1a07000) {
                // if_8f60dfbc_0_true
                // branch -> 0x8f60dfcc
                // 0x8f60dfcc
                v10 = *(int32_t *)(v1 + 12);
                result = *a1;
                *(int32_t *)(v3 + 20) = result;
                *(int32_t *)(v3 + 36) = v10 * *(int32_t *)(v1 + 16) / 8;
                *(int32_t *)(v3 + 4) = v6;
                *a3 = v9;
                *(int32_t *)(v3 + 12) = v9;
                *(int32_t *)(v3 + 8) = 0;
                *(int32_t *)(v3 + 16) = 0;
                *(int32_t *)(v3 + 48) = 0x2243f;
                *(int32_t *)(v3 + 52) = 0x20001;
                *(int32_t *)(v3 + 56) = 0x2000 * *(int32_t *)(v2 + 24) & 0x6000;
                // 0x8f60e040
                return result;
            }
        }
        // 0x8f60dfc4
        v8 = *a2 / 2;
        // branch -> 0x8f60dfcc
    }
    // 0x8f60dfcc
    v10 = *(int32_t *)(v1 + 12);
    result = *a1;
    *(int32_t *)(v3 + 20) = result;
    *(int32_t *)(v3 + 36) = v10 * *(int32_t *)(v1 + 16) / 8;
    *(int32_t *)(v3 + 4) = v6;
    *a3 = v9;
    *(int32_t *)(v3 + 12) = v9;
    *(int32_t *)(v3 + 8) = v8;
    *(int32_t *)(v3 + 16) = 0;
    *(int32_t *)(v3 + 48) = 0x2243f;
    *(int32_t *)(v3 + 52) = 0x20001;
    *(int32_t *)(v3 + 56) = 0x2000 * *(int32_t *)(v2 + 24) & 0x6000;
    // 0x8f60e040
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 06:44:38
