//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t mmc_get_ext_csd_isra_11(char * a1, int32_t * a2);
int32_t mmc_set_drv_type(char * a1, int32_t a2, uint32_t a3, int32_t a4);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f609518 - 0x8f6095ef
int32_t mmc_get_ext_csd_isra_11(char * a1, int32_t * a2) {
    int32_t v1 = (int32_t)a2; // R4
    char * v2 = memalign(64, 512); // 0x8f609540
    *(int32_t *)v1 = (int32_t)v2;
    int32_t v3;
    char * v4 = (char *)v3;
    int32_t v5;
    if (v2 == NULL) {
        // 0x8f609550
        _panic(0, (int32_t)"ASSERT FAILED at (%s:%d): %s\n", (int32_t)"platform/msm_shared/mmc_sdhci.c", 676, (int32_t)"card->ext_csd", 0, v5);
        v4 = "card->ext_csd";
        // branch -> 0x8f60956c
    }
    // 0x8f60956c
    memset((char *)*(int32_t *)v1, 0, 4);
    memset((char *)&v5, 0, 64);
    int32_t v6 = *(int32_t *)v1; // 0x8f60958c
    v5 = 8;
    int32_t result = sdhci_send_command((char *)(int32_t)a1, (int32_t)&v5, v6, 1, (int32_t)v4, 0, 8, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0); // 0x8f6095c0
    // 0x8f6095d8
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void * memalign(size_t alignment, size_t size);
// void * memset(void * s, int c, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 06:33:49
