//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t bd65060_read_reg(int32_t a1, int32_t a2);
int32_t bd65b60_backlight_off(int32_t a1, int32_t a2, int32_t a3);
int32_t bd65b60_backlight_on(int32_t a1, int32_t a2, int32_t a3);
int32_t bd65b60_init(void);
int32_t get_brightness_59(int32_t a1, int32_t a2, int32_t a3);
int32_t get_brightness_63(int32_t a1, int32_t a2, int32_t a3);
int32_t get_max_brightness_60(int32_t a1, int32_t a2, int32_t a3);
int32_t get_max_brightness_64(int32_t a1, int32_t a2, int32_t a3);
int32_t lm3697_backlight_on(int32_t a1, int32_t a2, int32_t a3);
int32_t lp8556_init(void);
int32_t oem_bd65060(int32_t a1, int32_t a2, int32_t a3);
int32_t oem_bd65060_usage(int32_t a1, int32_t a2, int32_t a3);
int32_t oem_lp8556_usage(int32_t a1, int32_t a2, int32_t a3);
int32_t set_brightness_62(uint32_t a1, int32_t a2);
int32_t set_brightness_66(uint32_t a1, int32_t a2);
int32_t set_default_brightness_61(uint32_t a1, int32_t a2, int32_t a3);
int32_t set_default_brightness_65(uint32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g12 = 0; // R2
int32_t g13 = 0; // R4
int32_t g14 = 0; // R5
int32_t g15 = 0; // R6
bool g16 = false; // R7
int32_t g1 = 0x746e6300; // 0x8f6a4e20
int32_t g2 = 255; // 0x8f6aca7c
int32_t g3 = 255; // 0x8f6aca84
int32_t g4 = 255; // 0x8f6aca88
char * g5 = "\x01"; // 0x8f6aca8c
int32_t g6 = 255; // 0x8f6aca90
int32_t g7 = 255; // 0x8f6aca94
int32_t g8 = 0; // 0x8f6e0a88
int32_t g9 = 0; // 0x8f6e0a94
int32_t g10 = 0; // 0x8f6e0a98
int32_t g11 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f6405e0 - 0x8f64070f
int32_t oem_bd65060(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = g13; // 0x8f6405e4
    int32_t v2 = g16 ? (int32_t)&g11 : 0; // 0x8f6405e4
    int32_t v3 = a1 - 1; // 0x8f6405e8
    int32_t v4 = g11;
    g13 = a2;
    int32_t v5 = 0; // bp-29
    if (v3 <= 0) {
        // 0x8f640624
        oem_bd65060_usage(a1, a2, 0);
        // branch -> 0x8f6406d8
        // 0x8f6406d8
        // branch -> 0x8f6406dc
        // 0x8f6406dc
        if (v4 != g11) {
            // 0x8f6406ec
            __stack_chk_fail();
            // branch -> 0x8f6406f0
        }
        // 0x8f6406f0
        return 1;
    }
    int32_t str = *(int32_t *)(a2 + 4); // 0x8f64060c
    int32_t result;
    if (strcmp((char *)str, "help") == 0) {
        // 0x8f64060c
        // branch -> 0x8f640624
        // 0x8f640624
        oem_bd65060_usage(0, (int32_t)"help", 0);
        // branch -> 0x8f6406d8
        // 0x8f6406d8
        result = 1;
        // branch -> 0x8f6406dc
    } else {
        int32_t v6 = (int32_t)"rd"; // R1
        int32_t v7; // 0x8f640648
        if (strcmp((char *)str, "rd") == 0) {
            // 0x8f640640
            if (v3 != 1) {
                int32_t v8 = atol((char *)*(int32_t *)(g13 + 8)) % 256; // 0x8f64065c
                g13 = v8;
                int32_t v9 = bd65060_read_reg(v8, (int32_t)&v5); // 0x8f640664
                result = 3;
                if (v9 == 0) {
                    // 0x8f640678
                    fboot_info((int32_t)"INFO", (int32_t)"0x%02X = 0x%02X", g13, 0x1000000 * v5 / 0x1000000, a1, v4, a3, v1, g14, g15, v2);
                    // branch -> 0x8f6406d8
                    // 0x8f6406d8
                    result = 1;
                    // branch -> 0x8f6406dc
                }
                // 0x8f6406dc
                if (v4 != g11) {
                    // 0x8f6406ec
                    __stack_chk_fail();
                    // branch -> 0x8f6406f0
                }
                // 0x8f6406f0
                return result;
            }
            v7 = 0;
        } else {
            // 0x8f640690
            v6 = (int32_t)"wr";
            int32_t strcmp_rc = strcmp((char *)str, "wr"); // 0x8f640698
            if (strcmp_rc == 0 && v3 >= 3) {
                uint32_t str_as_l = atol((char *)*(int32_t *)(g13 + 8)); // 0x8f6406b0
                uint32_t str_as_l2 = atol((char *)*(int32_t *)(g13 + 12)); // 0x8f6406bc
                v5 = 0x1000000 * str_as_l2 / 0x1000000;
                int32_t v10 = bd65060_write_reg(str_as_l % 256, str_as_l2 % 256, 0, (int32_t)&g11); // 0x8f6406cc
                result = 3;
                if (v10 == 0) {
                    // 0x8f6406d8
                    result = 1;
                    // branch -> 0x8f6406dc
                }
                // 0x8f6406dc
                if (v4 != g11) {
                    // 0x8f6406ec
                    __stack_chk_fail();
                    // branch -> 0x8f6406f0
                }
                // 0x8f6406f0
                return result;
            }
            v7 = strcmp_rc;
        }
        // 0x8f640648
        oem_bd65060_usage(v7, v6, 0);
        result = 3;
        // branch -> 0x8f6406dc
    }
    // 0x8f6406dc
    if (v4 != g11) {
        // 0x8f6406ec
        __stack_chk_fail();
        // branch -> 0x8f6406f0
    }
    // 0x8f6406f0
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// long int atol(const char * nptr);
// int strcmp(const char * s1, const char * s2);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 17
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 18:46:56
