//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t cid_init(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
char * cid_verify_sig(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t clk_enable(int32_t a1, int32_t a2);
int32_t clk_set_rate(int32_t a1);
int32_t dbval_memcmp_value(int32_t a1, int32_t a2, int32_t a3);
int32_t dbval_validate_datablock(int32_t a1, int32_t a2, int32_t a3, char * a4);
int32_t disable_gpio_107_irq(int32_t a1);
int32_t display_draw_horizontal_line(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t display_draw_screen_line_alignment(int32_t a1);
int32_t fan54046_chg_enable(int32_t result, int32_t a2, int32_t a3);
int32_t fan54046_init(void);
int32_t fdt_add_subnode(int32_t a1, int32_t a2, char * str, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
int32_t fdt_open_into(int32_t a1, char * a2, int32_t a3);
void function_8f64b418(void);
void function_8f64b470(int32_t a1, int32_t a2, int32_t a3);
void function_8f67b2cc(int32_t a1, char * a2, int32_t a3);
int32_t get_canary(int32_t a1);
int32_t get_ddr_start(void);
int32_t mcs_DER_locate(int16_t a1, int16_t * a2, int32_t a3, int32_t a4);
int32_t mcs_DER_recordLength(int32_t a1);
int32_t mcs_habp_rsa(int32_t a1, int32_t a2, int32_t a3, int32_t a4, uint32_t a5);
int32_t mcs_habp_rsa_crt_core(int32_t a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7);
int32_t mdp_disable(int32_t a1);
int32_t mdss_dsi_panel_power_on_reset(int32_t a1, int32_t a2);
int32_t mdss_dual_dsi_cmds_tx(int32_t a1, int32_t a2);
int32_t mipi_dsi_cmds_tx(int32_t a1, int32_t a2);
int32_t msm_gpio_int_uninit(int32_t a1);
int32_t platform_get_smem_base_addr(void);
char * scm_xpu_err_fatal_init(int32_t a1);
int32_t store_partition(int32_t a1, int32_t a2, int64_t a3, int32_t a4, int32_t a5, int32_t a6, int32_t a7, int32_t a8, int32_t a9);

// --------------------- Global Variables ---------------------

int32_t g17 = 0; // LR
int32_t g18 = 0; // R0
int32_t g19 = 0; // R1
int32_t g20 = 0; // R10
int32_t g21 = 0; // R11
int32_t g22 = 0; // R12
int32_t g23 = 0; // R2
int32_t g24 = 0; // R3
int32_t g25 = 0; // R4
int32_t g26 = 0; // R5
int32_t g27 = 0; // R6
int32_t g28 = 0; // R7
int32_t g29 = 0; // R8
int32_t g30 = 0; // R9
int32_t g1 = -0x16d2bff0; // 0x8f6663f0
int32_t g2 = -0x16d2bff0; // 0x8f666470
int32_t g3 = -0x16d2bfd0; // 0x8f6664f4
char * g4 = "\x39\x02\x63\x69\x64\x5f\x67\x65\x74\x5f\x63\x69\x64\x5f\x64\x61\x74\x61\x20\x2d\x20\x53\x54\x41\x52\x54\x0a"; // 0x8f6a54e8
char * g5 = "\x06"; // 0x8f6acab0
int16_t * g6 = (int16_t *)0xffff; // 0x8f6affa4
int32_t g7 = 0; // 0x8f6e0aac
int32_t g8 = 0; // 0x8f6e0c00
int32_t g9 = 0; // 0x8f6e0c08
int32_t g10 = 0; // 0x8f6e0c38
char * g11; // 0x8f6e0c40
char * g12; // 0x8f70da9b
int32_t g13 = 0; // 0x8f710ed4
int32_t g14 = 0; // 0x8f710ed8
int32_t g15 = 0; // 0x8f7112f4
int32_t g16 = 0; // 0x8f7125ec

// ------------------------ Functions -------------------------

// Address range: 0x8f6173a0 - 0x8f617513
char * scm_xpu_err_fatal_init(int32_t a1) {
    int32_t v1 = 0; // bp-104
    int32_t v2;
    int32_t v3 = &v2; // 0x8f6173cc_0
    memset((char *)&v2, 0, 64);
    int32_t v4; // bp-88
    int32_t v5 = &v4; // 0x8f6173e4_0
    v4 = 0;
    int32_t v6; // R2
    uint32_t v7;
    int32_t v8; // 0x8f6174e82
    if (v7 % 256 == 1) {
        // 0x8f61746c
        v2 = 0x2000c0e;
        v6 = v3;
        v1 = v4;
        v8 = scm_call2(v3, v5, v3, v5, g21, g17);
        // branch -> 0x8f6174b0
    } else {
        int32_t v9 = 0;
        int32_t v10 = &v9; // 0x8f617438_0
        v6 = v10;
        v8 = scm_call(12, 14, v10, 8, (int32_t)&v1);
        // branch -> 0x8f6174b0
    }
    // 0x8f6174b0
    int32_t v11;
    if (v8 == 0) {
        // 0x8f6174d8
        print_log(1, -0x7097f240, v6, 0, g21, g17, v11, 0, 0, 0, 0, 0, 0);
        // branch -> 0x8f6174e8
    } else {
        int32_t v12 = v1; // 0x8f6174bc
        print_log(-1, -0x7097f274, v12, v12, g21, g17, v11, 0, 0, 0, 0, 0, 0);
        // branch -> 0x8f6174e8
    }
    // 0x8f6174e8
    if (*(int32_t *)-0x708eed0c != *(int32_t *)-0x708eed0c) {
        // 0x8f617508
        __stack_chk_fail();
        // branch -> 0x8f61750c
    }
    // 0x8f61750c
    return (char *)v8;
}

// --------------- Statically Linked Functions ----------------

// ulldiv_t __aeabi_uldivmod(unsigned long long a, unsigned long long b);
// void __stack_chk_fail(void);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// int rand(void);
// int sprintf(char * restrict s, const char * restrict format, ...);
// char * strcat(char * restrict dest, const char * restrict src);
// size_t strlen(const char * s);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 30
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 19:29:08
