//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t smem_copy_ram_ptable(char * a1);
int32_t smem_ram_ptable_init_v1(void);

// --------------------- Global Variables ---------------------

int32_t g8 = 0; // R4
bool g9 = false; // R5
int32_t g1 = 0x65440030; // 0x8f69c66f
char * g2; // 0x8f6b50a8
int32_t g3 = 0; // 0x8f6b58c0
int32_t g4 = 0; // 0x8f6b58c4
int32_t g5 = 0; // 0x8f6b58c8
int32_t g6 = 0; // 0x8f6b58d0
int32_t g7 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f604894 - 0x8f6049b7
int32_t smem_ram_ptable_init_v1(void) {
    // 0x8f604894
    int32_t v1;
    int32_t v2 = v1; // bp-32
    int32_t v3 = g8; // 0x8f604894
    int32_t v4 = g9 ? (int32_t)&g7 : 0; // 0x8f604894
    int32_t v5 = 0; // 0x8f604894
    int32_t v6 = 0; // 0x8f604894
    int32_t v7 = g7;
    g9 = true;
    int32_t v8 = 8; // R3
    int32_t v9;
    int32_t v10 = smem_read_alloc_entry_offset(402, (int32_t)&v2, 4, 8, v9, 0, v1, v7, 0, v3, v4, v5); // 0x8f6048c0
    if (v10 != 0) {
        // 0x8f604978
        if (v7 != g7) {
            // 0x8f604988
            __stack_chk_fail();
            // branch -> 0x8f60498c
        }
        // 0x8f60498c
        return 0;
    }
    int32_t v11 = v2; // 0x8f6048d4
    int32_t v12; // 0x8f6049702
    int32_t v13; // 0x8f60492c
    int32_t v14; // 0x8f604924
    switch (v11) {
        default: {
            // 0x8f6048ec
            print_log(-1, (int32_t)"ERROR: Wrong smem_ram_ptable version: %u", v11, v8, v9, 0, v11, v7, 0, v3, v4, v5, v6);
            v8 = 242;
            int32_t v15 = _panic(0, (int32_t)"ASSERT FAILED at (%s:%d): %s\n", (int32_t)"platform/msm_shared/smem_ptable.c", 242, (int32_t)&g1, 0, v2); // 0x8f604910
            v13 = v2;
            v14 = v15 & -0x10000 | 402;
            v12 = &g1;
            // branch -> 0x8f604920
            break;
        }
        case 1: {
            // 0x8f60491c
            v13 = 1;
            v10 = 2072;
            v14 = 402;
            v12 = v9;
            // branch -> 0x8f604920
            break;
        }
        case 0: {
            // if_8f6048e4_0_true
            v13 = 0;
            v10 = 1816;
            v14 = 402;
            v12 = v9;
            // branch -> 0x8f604920
            break;
        }
    }
    // 0x8f604920
    g8 = &g3;
    int32_t v16 = smem_read_alloc_entry(v14, (int32_t)&g3, v10, v8, v12, 0, v13, v7, 0); // 0x8f60492c
    int32_t result = 0;
    if (v16 == 0) {
        // 0x8f604938
        if (g3 == -0x625a1f58) {
            // 0x8f604948
            if (g4 == -0x50613b1e) {
                // 0x8f604958
                smem_copy_ram_ptable((char *)g8);
                print_log(2, (int32_t)"smem ram ptable found: ver: %u len: %u\n", g5, g6, v12, 0, v2, v7, 0, v3, v4, v5, v6);
                result = 1;
                // branch -> 0x8f604978
            } else {
                result = 0;
            }
        } else {
            result = 0;
        }
    }
    // 0x8f604978
    if (v7 != g7) {
        // 0x8f604988
        __stack_chk_fail();
        // branch -> 0x8f60498c
    }
    // 0x8f60498c
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 05:55:53
