//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __utag_gets_constprop_3(char * a1, int32_t a2);
int32_t target_early_init(void);

// --------------------- Global Variables ---------------------

int32_t g3 = 0; // R2
int32_t g1 = 0x2020003a; // 0x8f686ac4
int32_t g2 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f6003c4 - 0x8f600497
int32_t target_early_init(void) {
    int32_t v1;
    int32_t v2;
    int32_t v3; // 0x8f600414
    if (target_mot_prod_id((char *)0, 0, g3, g2) == 68) {
        // 0x8f6003e8
        gpio_tlmm_config(36, 0, 1, 1, 0, 1, 0);
        gpio_set_dir(36, 2, 1, 1);
        v3 = 1;
        gpio_set_value(36, v3, 1, 1);
        mdelay(5, v3, 1, 1);
        v2 = 0;
        v1 = 1;
        // branch -> 0x8f600424
    }
    int32_t v4 = 0; // R3
    int32_t v5 = 0;
    int32_t v6 = get_uart_setting((int32_t)&v5, v3, 1, 0, v2, v1, 0); // 0x8f600434
    int32_t v7; // 0x8f600468
    int32_t v8; // 0x8f6004684
    int32_t v9; // 0x8f60045c
    if (v6 == 0) {
        // 0x8f600424
        v7 = v4;
        v9 = v5;
        v8 = 0;
        // branch -> 0x8f60045c
    } else {
        // 0x8f600440
        print_log(1, (int32_t)"Not get uart setting, use default\n", 1, v4, v2, v1, 0, v5, 0, g2, 0, 0, 0);
        v5 = 0x78af000;
        v4 = 1;
        v7 = 1;
        v9 = 0x78af000;
        v8 = 1;
        // branch -> 0x8f60045c
    }
    int32_t result = uart_dm_init(v8, 0, v9, v7, v2, v1, 0, v9, v8); // 0x8f600468
    logger_early_init(result, 0, v9, v4, v2, v1, 0);
    // 0x8f600484
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// char * strncpy(char * restrict dest, const char * restrict src, size_t n);
// char * strrchr(char * s, int c);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 05:43:44
