//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

// ------------------- Function Prototypes --------------------

int32_t turn_off_backlight(int32_t result, int32_t a2, int32_t a3);
int32_t turn_on_backlight(int32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g5 = 0; // LR
int32_t g6 = 0; // R0
int32_t g7 = 0; // R4
bool g8 = false; // R5
int32_t g1 = 0; // 0x8f6b8c84
int32_t (*g2)() = NULL; // 0x8f6b8c8c
int32_t (*g3)() = NULL; // 0x8f6b8c90
int32_t g4 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f617a8c - 0x8f617b27
int32_t turn_on_backlight(int32_t a1, int32_t a2, int32_t a3) {
    int32_t v1 = g7; // 0x8f617a8c
    int32_t v2 = g8 ? (int32_t)&g4 : 0; // 0x8f617a8c
    int32_t v3 = g5; // 0x8f617a8c
    g7 = &g4;
    int32_t v4 = g4;
    g8 = true;
    int32_t v5;
    int32_t result = print_log(2, (int32_t)"%s is called\n", (int32_t)"turn_on_backlight", v4, a1, v4, a3, v1, v2, v3, v5, 0, 0); // 0x8f617aac
    g6 = result;
    if (g1 == 0) {
        // 0x8f617af8
        if (v4 == g4) {
            // 0x8f617b0c
            return result;
        }
    } else {
        int32_t (*v6)() = g2;
        if (v6 != NULL) {
            // 0x8f617acc
            g5 = -0x709e8530;
            v6();
            // branch -> 0x8f617ad0
        }
        // 0x8f617ad0
        if (v4 == g4) {
            // 0x8f617ae0
            return print_log(2, (int32_t)"%s is done \n", (int32_t)"turn_on_backlight", v4, v1, v2, v3, v5, 0, 0, 0, 0, 0);
        }
    }
    // 0x8f617b08
    __stack_chk_fail();
    // branch -> 0x8f617b0c
    // 0x8f617b0c
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 07:43:54
