//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <ctype.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t __aeabi_idivmod(int32_t a1, int32_t a2);
int32_t __utag_describe(int32_t a1, int32_t a2, int32_t a3);
int32_t arg_free(char * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5);
int32_t atoull(char * a1, int32_t a2);
int32_t decode_hw_type(char * a1, int32_t a2, int32_t a3);
int32_t display_render_done(int32_t a1, int32_t a2);
int32_t fdt_pack(int32_t a1, int32_t a2, int32_t a3);
int32_t font_draw_char_moto(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
int32_t font_draw_char_moto_horizontal(int32_t * a1, int32_t a2, int32_t a3, int32_t a4, int32_t a5, int32_t a6);
void function_8f649e14(void);
void function_8f67b584(void);
int32_t get_timestamp(int32_t a1, int32_t a2, int32_t a3);
int32_t initialize_montgomery_alg(int32_t * a1, int32_t a2, int32_t a3);
int32_t is_charging_enabled(int32_t a1, int32_t a2, int32_t a3);
int32_t mot_sst_get_unlock_data_length(int32_t a1, int32_t a2, int32_t a3);
int32_t mot_sst_is_warranty_void(int32_t a1);
int32_t mot_sst_set_state_values_for_nonhlos(void);
int32_t mot_sst_validate_hash_password(int32_t a1, char * a2);
int32_t mp_mont_sqr(int32_t * a1, int32_t result, int32_t a3);
int32_t pm8x41_gpio_config(int32_t a1, int32_t * a2, int32_t a3);
int32_t pm8x41_set_boot_done(int32_t a1);
int32_t pmic_set_chg_set_mode(char a1, int32_t a2, int32_t a3);
int32_t qtimer_irq(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t SecGetSVNum(uint32_t a1, int32_t a2);
int32_t set_logo(char a1, int32_t a2, int32_t a3);
int32_t sod_update(char * a1, int32_t a2, int32_t a3);
int32_t target_set_prod_id(char * a1, int32_t a2, int32_t a3);
int32_t udc_start(int32_t a1, int32_t a2);
int32_t udc_stop(int32_t a1, int32_t a2);
int32_t wait_clogo(int32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g16 = 0; // LR
int32_t g17 = 0; // R0
int32_t g18 = 0; // R1
int32_t g19 = 0; // R10
int32_t g20 = 0; // R2
int32_t g21 = 0; // R3
int32_t g22 = 0; // R4
int32_t g23 = 0; // R5
int32_t g24 = 0; // R6
int32_t g25 = 0; // R7
int32_t g26 = 0; // R8
int32_t g27 = 0; // R9
int32_t g1 = -0x16d2bf10; // 0x8f60569c
int32_t g2 = -1; // 0x8f6ac0e0
int32_t g3 = 1; // 0x8f6ac0f0
char * g4 = "\x01"; // 0x8f6afe10
int32_t g5 = 0; // 0x8f6b792c
char * g6; // 0x8f6b794c
int32_t g7 = 0; // 0x8f6b8abc
int32_t g8 = 0; // 0x8f6b8ac0
int32_t g9 = 0; // 0x8f6b8ac4
int32_t (*g10)(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t) = NULL; // 0x8f6b8ac8
int32_t g11 = 0; // 0x8f6b8acc
int32_t g12 = 0; // 0x8f6e08b8
char * g13; // 0x8f6e08f9
char * g14; // 0x8f6e0b60
int32_t g15 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f649f1c - 0x8f649ffb
int32_t atoull(char * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    int32_t v2 = g23; // 0x8f649f1c
    int32_t v3 = g25; // 0x8f649f1c
    int32_t v4 = g15;
    int32_t v5 = v1 + 1; // 0x8f649f4c
    int32_t result; // R4
    int32_t v6; // R9
    if (*a1 == 48) {
        // 0x8f649f4c
        if (*(char *)v5 == 120) {
            // if_8f649f54_0_true
            result = 0;
            g23 = 0;
            v6 = v1 + 3;
            char v7 = *(char *)(v1 + 2); // 0x8f649f647
            if (v7 == 0) {
                // 0x8f649fd4
                if (v4 != g15) {
                    // 0x8f649fec
                    __stack_chk_fail();
                    // branch -> 0x8f649ff0
                }
                // 0x8f649ff0
                g23 = v2;
                g25 = v3;
                return result;
            }
            int32_t c = v7; // 0x8f649f6410
            while (true) {
                // 0x8f649f70
                if (isxdigit(c) != 0) {
                    int32_t v8 = 16 * g23; // 0x8f649f80
                    g25 = v8;
                    int32_t v9 = hexval((int32_t)*(char *)(v6 - 1), a2); // 0x8f649f84
                    uint32_t v10 = result; // 0x8f649f88
                    int32_t v11 = v10 / 0x10000000 | v8; // 0x8f649f88
                    g25 = v11;
                    uint32_t v12 = 16 * v10; // 0x8f649f8c
                    int32_t v13 = v12 + v9; // 0x8f649f90
                    result = v13;
                    g23 = v11 + (v9 >> 31) + (int32_t)(v13 < v12);
                    int32_t v14 = v6; // 0x8f649f64
                    v6 = v14 + 1;
                    char v15 = *(char *)v14; // 0x8f649f64
                    if (v15 == 0) {
                        // break -> 0x8f649fd4
                        break;
                    }
                    c = v15;
                    // continue -> 0x8f649f70
                    continue;
                }
            }
            // 0x8f649fd4
            if (v4 != g15) {
                // 0x8f649fec
                __stack_chk_fail();
                // branch -> 0x8f649ff0
            }
            // 0x8f649ff0
            g23 = v2;
            g25 = v3;
            return result;
        }
    }
    // 0x8f649f38
    result = 0;
    g23 = 0;
    int32_t v16 = 10; // R10
    v6 = v5;
    char v17 = *a1; // 0x8f649fc814
    if (v17 == 0) {
        // 0x8f649fd4
        if (v4 != g15) {
            // 0x8f649fec
            __stack_chk_fail();
            // branch -> 0x8f649ff0
        }
        // 0x8f649ff0
        g23 = v2;
        g25 = v3;
        return result;
    }
    int32_t c2 = v17; // 0x8f649fc817
    while (true) {
        // 0x8f649f9c
        if (isdigit(c2) != 0) {
            uint64_t v18 = (int64_t)v16 * (int64_t)result; // 0x8f649fa8
            uint32_t v19 = (int32_t)v18; // 0x8f649fa8
            int32_t v20 = v6; // 0x8f649fac
            g25 = 0;
            uint32_t v21 = v19 - 48; // 0x8f649fb4
            int32_t v22 = v21 + (int32_t)*(char *)(v20 - 1); // 0x8f649fc0
            result = v22;
            g23 = g23 * v16 + (int32_t)(v18 / 0x100000000) + (int32_t)(v19 < 48) + (int32_t)(v22 < v21);
            v6 = v20 + 1;
            char v23 = *(char *)v20; // 0x8f649fc8
            if (v23 == 0) {
                // break -> 0x8f649fd4
                break;
            }
            c2 = v23;
            // continue -> 0x8f649f9c
            continue;
        }
        // 0x8f649fd4
        if (v4 != g15) {
            // 0x8f649fec
            __stack_chk_fail();
            // branch -> 0x8f649ff0
        }
        // 0x8f649ff0
        g23 = v2;
        g25 = v3;
        return result;
    }
    // 0x8f649fd4
    if (v4 != g15) {
        // 0x8f649fec
        __stack_chk_fail();
        // branch -> 0x8f649ff0
    }
    // 0x8f649ff0
    g23 = v2;
    g25 = v3;
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void free(void * ptr);
// int isdigit(int c);
// int isxdigit(int c);
// void * malloc(size_t size);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 30
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 19:31:19
