//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t board_pmic_target(uint32_t a1, int32_t a2, int32_t a3);
int32_t board_soc_version(int32_t a1, int32_t a2, int32_t a3);
char * dbval_memcpy(char * a1, char * a2, int32_t a3);
int32_t dbval_read_flash_uid(char * a1, int32_t * a2, int32_t a3);
char * for_each_token(char * str, char * a2, int32_t (*a3)(int32_t), int32_t a4);
int32_t get_hw_radio(int32_t a1, int32_t a2, int32_t a3);
int32_t get_uart_setting(int32_t * a1);
int32_t get_verified_enabled(void);
int32_t gic_mask_interrupt(uint32_t a1);
void gic_platform_fiq(int32_t a1);
int32_t is_fastboot_screen(int32_t a1, int32_t a2, int32_t a3);
int32_t is_screen(char * str);
int32_t mipi_detect(int32_t a1, int32_t a2);
int32_t mipi_dsi_panel_initialize(int32_t a1, int32_t a2, int32_t a3);
int32_t mmc_get_device_blocksize(void);
int32_t mmc_get_psn(int32_t a1, int32_t a2);
char * mmc_sd_card_init(char * a1, int32_t * a2);
char * mmc_sd_set_bus_width(char * a1, int32_t * a2, int32_t a3);
int32_t mp_subb(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t platform_get_phys_to_virt_mapping(int32_t a1, int32_t a2, int32_t a3);
int32_t platform_get_virt_to_phys_mapping(int32_t a1, int32_t a2, int32_t a3);
int32_t platform_is_msm8929(int32_t a1, int32_t a2);
int32_t platform_is_msm8939(int32_t a1, int32_t a2);
int32_t smb1359_config_apsd(int32_t a1, int32_t a2);
int32_t smb1359_config_fastchg_current(int32_t a1, int32_t a2);
char * smem_get_ram_ptable_entry(char * a1, int32_t a2, int32_t a3);
int32_t smem_ram_ptable_init_v1(void);
int32_t unit_modular_inverse(int64_t a1);
int32_t usb_cable_is_charger(int32_t a1, int32_t a2);
int32_t utags_set_cmdline(char * a1, char * a2, int32_t a3, int32_t a4);

// --------------------- Global Variables ---------------------

int32_t g17 = 0; // LR
int32_t g18 = 0; // R0
int32_t g19 = 0; // R1
int32_t g20 = 0; // R2
int32_t g21 = 0; // R3
int32_t g22 = 0; // R4
int32_t g23 = 0; // R5
int32_t g24 = 0; // R6
int32_t g25 = 0; // R7
int32_t g1 = -0x16d2b810; // 0x8f6554ac
int32_t g2 = 0x6d0f0703; // 0x8f67f1bd
int32_t g3 = 0x65440030; // 0x8f69c66f
int32_t g4 = 0; // 0x8f6ac068
int32_t g5 = 0; // 0x8f6ac070
int32_t g6 = -1; // 0x8f6ac1f0
int32_t g7 = -1; // 0x8f6ac1f4
int32_t g8 = -1; // 0x8f6ac200
int32_t g9 = -1; // 0x8f6ac214
int32_t g10 = 0; // 0x8f6b50a8
int32_t g11 = 0; // 0x8f6b58c0
int32_t g12 = 0; // 0x8f6b58c4
int32_t g13 = 0; // 0x8f6b58c8
int32_t g14 = 0; // 0x8f6b58d0
int32_t g15 = 0; // 0x8f6e0854
int32_t g16 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f610548 - 0x8f61069f
int32_t mipi_detect(int32_t a1, int32_t a2) {
    // 0x8f610548
    int32_t v1;
    int32_t v2 = v1; // bp-376
    g23 = a1;
    int32_t v3 = g16;
    g24 = a2;
    g25 = &g16;
    if (a1 == 0) {
        // 0x8f610660
        int32_t result; // 0x8f610678_2
        result = 0;
        // 0x8f610674
        return result;
    }
    // 0x8f61056c
    g19 = (int32_t)"%s is called \n";
    g22 = *(int32_t *)(a1 + 500);
    int32_t v4;
    print_log(2, (int32_t)"%s is called \n", (int32_t)"mipi_detect", (int32_t)&g16, v4, 0, v1, 0, 0, 0, 0, 0, 0);
    int32_t v5 = *(int32_t *)(g23 + 504); // 0x8f610588
    *(int32_t *)v5 = -0x7ce00000;
    int32_t v6 = mdp_set_revision(g24, (int32_t)"%s is called \n", -0x7ce00000, v5); // 0x8f610590
    g20 = v6;
    int32_t v7 = &v2; // 0x8f610594_0
    g18 = v7;
    int32_t v8 = *(int32_t *)(g23 + 524); // 0x8f610598
    g21 = v8;
    g17 = -0x709efa60;
    ((int32_t (*)(int32_t, int32_t, int32_t))v8)(v7, v6, v8);
    int32_t v9 = *(int32_t *)(g23 + 532); // 0x8f6105a0
    g21 = v9;
    g17 = -0x709efa58;
    ((int32_t (*)(int32_t))v9)(v9);
    g18 = 1;
    int32_t v10 = *(int32_t *)(g23 + 556); // 0x8f6105ac
    g21 = v10;
    g19 = v7;
    g17 = -0x709efa48;
    ((int32_t (*)(int32_t, int32_t, int32_t))v10)(1, v7, v10);
    int32_t v11 = g22; // 0x8f6105b8
    char v12 = *(char *)v11; // 0x8f6105b8
    int32_t v13 = v12; // 0x8f6105b8
    int32_t v14 = v4; // 0x8f61065c4
    int32_t v15; // 0x8f610640
    int32_t result2; // 0x8f61065c
    int32_t v16;
    int32_t v17;
    int32_t v18;
    int32_t v19;
    int32_t v20; // 0x8f610600
    int32_t v21; // 0x8f61061c
    int32_t v22; // 0x8f610624
    switch (v12) {
        case 1: {
            // if_8f6105c0_0_true
            // branch -> 0x8f6105f4
            // 0x8f6105f4
            mdss_dsi_phy_init(v11, 0x1a98000, 0x1a98500, g21, v4, 0, v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
            v16 = 0x1000000 * v18;
            v20 = v16 / 0x1000000;
            if ((v16 || 0xffffff) >= 0x1ffffff) {
                // 0x8f61060c
                mdss_dsi_phy_init(g22, 0x1aa0000, 0x1aa0500, v20, v4, 0, v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                // branch -> 0x8f61061c
            }
            // 0x8f61061c
            v21 = 0x1000000 * v19 / 0x1000000;
            v22 = 0x1000000 * v17 / 0x1000000;
            g21 = 0;
            mdss_dsi_host_init(g22, v20, v22, 0, v21, 0, v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
            v15 = mdss_dsi_phy_contention_detection(g22, 0x1a98500, v22, g21, v21, 0, v2, 0);
            mdss_dsi_panel_power_on_reset(v15, 0x1a98500, v22, g21);
            mdss_dsi_panel_identify(0, 0x1a98500, v22, g21, v21, 0, v2, 0, 0, 0);
            v14 = v21;
            // branch -> 0x8f610650
            break;
        }
        case 2: {
            int32_t v23 = g24 & -9; // 0x8f6105d0
            g24 = v23;
            if (v23 == 5) {
                // 0x8f6105f4
                mdss_dsi_phy_init(v11, 0x1a98000, 0x1a98500, g21, v4, 0, v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                v16 = 0x1000000 * v18;
                v20 = v16 / 0x1000000;
                if ((v16 || 0xffffff) >= 0x1ffffff) {
                    // 0x8f61060c
                    mdss_dsi_phy_init(g22, 0x1aa0000, 0x1aa0500, v20, v4, 0, v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                    // branch -> 0x8f61061c
                }
                // 0x8f61061c
                v21 = 0x1000000 * v19 / 0x1000000;
                v22 = 0x1000000 * v17 / 0x1000000;
                g21 = 0;
                mdss_dsi_host_init(g22, v20, v22, 0, v21, 0, v2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
                v15 = mdss_dsi_phy_contention_detection(g22, 0x1a98500, v22, g21, v21, 0, v2, 0);
                mdss_dsi_panel_power_on_reset(v15, 0x1a98500, v22, g21);
                mdss_dsi_panel_identify(0, 0x1a98500, v22, g21, v21, 0, v2, 0, 0, 0);
                v14 = v21;
                // branch -> 0x8f610650
            } else {
                // 0x8f6105e0
                mipi_dsi_phy_init(v11, v7, v13, g21, v4, 0, v2, 0);
                mipi_dsi_panel_initialize(g22, 0, v13);
                v14 = v4;
                // branch -> 0x8f610650
            }
            // 0x8f610650
            result2 = print_log(2, (int32_t)"%s is done\n", (int32_t)"mipi_detect", g21, v14, 0, v2, 0, 0, 0, 0, 0, 0);
            // branch -> 0x8f610660
            // 0x8f610660
            if (v3 != g16) {
                // 0x8f610670
                __stack_chk_fail();
                // branch -> 0x8f610674
            }
            // 0x8f610674
            return result2;
        }
    }
    // 0x8f610650
    result2 = print_log(2, (int32_t)"%s is done\n", (int32_t)"mipi_detect", g21, v14, 0, v2, 0, 0, 0, 0, 0, 0);
    // branch -> 0x8f610660
    // 0x8f610660
    if (v3 != g16) {
        // 0x8f610670
        __stack_chk_fail();
        // branch -> 0x8f610674
    }
    // 0x8f610674
    return result2;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void free(void * ptr);
// void * memcpy(void * restrict dest, const void * restrict src, size_t n);
// void * memset(void * s, int c, size_t n);
// char * strdup(const char * s);
// int strncmp(const char * s1, const char * s2, size_t n);
// char * strtok_r(char * restrict s, const char * restrict delim, char ** restrict save_ptr);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 30
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 19:44:26
