//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) 2017 Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

// ------------------- Function Prototypes --------------------

int32_t mmc_parse_response(char * a1, int32_t a2);
char * mmc_send_app_cmd_isra_5(char * a1, int32_t a2);

// --------------------- Global Variables ---------------------

int32_t g1 = 0; // 0x8f7112f4

// ------------------------ Functions -------------------------

// Address range: 0x8f609170 - 0x8f60923b
int32_t mmc_parse_response(char * a1, int32_t a2) {
    int32_t v1 = 0; // R4
    int32_t v2 = (int32_t)a1; // 0x8f609170_0
    int32_t result = g1;
    int32_t v3;
    if (a1 < NULL) {
        // if_8f609188_0_true
        // branch -> 0x8f6091f8
        // 0x8f6091f8
        print_log(-1, (int32_t)"Attempting to read or write beyond the Device capacity\n", (int32_t)&g1, v2, v2, result, v1, 0, v3, 0, 0, 0, 0);
        // branch -> 0x8f609200
        // 0x8f609200
        if (result != g1) {
            // 0x8f609210
            __stack_chk_fail();
            // branch -> 0x8f609214
        }
        // 0x8f609214
        return result;
    }
    // 0x8f609194
    if ((v2 & 0x40000000) != 0) {
        // if_8f609198_0_true
        // branch -> 0x8f6091f8
        // 0x8f6091f8
        print_log(-1, (int32_t)"The misaligned address did not match the block length used\n", (int32_t)&g1, v2, v2, result, v1, 0, v3, 0, 0, 0, 0);
        // branch -> 0x8f609200
        // 0x8f609200
        if (result != g1) {
            // 0x8f609210
            __stack_chk_fail();
            // branch -> 0x8f609214
        }
        // 0x8f609214
        return result;
    }
    // 0x8f6091a4
    if ((v2 & 0x20000000) != 0) {
        // if_8f6091a8_0_true
        // branch -> 0x8f6091f8
        // 0x8f6091f8
        print_log(-1, (int32_t)"The transferred bytes does not match the block length\n", (int32_t)&g1, v2, v2, result, v1, 0, v3, 0, 0, 0, 0);
        // branch -> 0x8f609200
        // 0x8f609200
        if (result != g1) {
            // 0x8f609210
            __stack_chk_fail();
            // branch -> 0x8f609214
        }
        // 0x8f609214
        return result;
    }
    // 0x8f6091b4
    if ((v2 & 0x4000000) != 0) {
        // if_8f6091b8_0_true
        // branch -> 0x8f6091f8
        // 0x8f6091f8
        print_log(-1, (int32_t)"Attempt to program a write protected block\n", (int32_t)&g1, v2, v2, result, v1, 0, v3, 0, 0, 0, 0);
        // branch -> 0x8f609200
        // 0x8f609200
        if (result != g1) {
            // 0x8f609210
            __stack_chk_fail();
            // branch -> 0x8f609214
        }
        // 0x8f609214
        return result;
    }
    // 0x8f6091c4
    int32_t v4; // 0x8f6091f8
    int32_t v5; // 0x8f6091f8
    if ((v2 & 0x100000) == 0) {
        // 0x8f6091d4
        if ((v2 & 0x80000) == 0) {
            int32_t v6 = v2 / 512 % 16; // 0x8f6091e4
            int32_t v7 = result;
            if (v6 != 4) {
                // 0x8f6091f0
                // branch -> 0x8f6091f8
                // 0x8f6091f8
                print_log(-1, (int32_t)"MMC card is not in TRAN state\n", (int32_t)&g1, v6, v2, result, v1, 0, v3, 0, 0, 0, 0);
                v7 = g1;
                // branch -> 0x8f609200
            }
            // 0x8f609200
            if (result != v7) {
                // 0x8f609210
                __stack_chk_fail();
                // branch -> 0x8f609214
            }
            // 0x8f609214
            return result;
        }
        v4 = (v2 & 0x80000) != 0;
        v5 = (int32_t)"A generic Device error\n";
    } else {
        // if_8f6091c8_0_true
        v4 = -1;
        v5 = (int32_t)"Device error occurred, which is not related to the host command\n";
        // branch -> 0x8f6091f8
    }
    // 0x8f6091f8
    print_log(v4, v5, (int32_t)&g1, v2, v2, result, v1, 0, v3, 0, 0, 0, 0);
    // branch -> 0x8f609200
    // 0x8f609200
    if (result != g1) {
        // 0x8f609210
        __stack_chk_fail();
        // branch -> 0x8f609214
    }
    // 0x8f609214
    return result;
}

// --------------- Statically Linked Functions ----------------

// void __stack_chk_fail(void);
// void * memset(void * s, int c, size_t n);

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: android-ndk-r8 (4.4.3 armv5te, armv7a(arm-linux-androideabi-gcc))
// Detected functions: 2
// Decompiler release: v2.2.1 (2016-09-07)
// Decompilation date: 2017-08-06 06:25:05
